{
 "title": "EIC ADC Dashboard",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(eric_oss_enm_fns:notifications_sent_total,site)"
    }
   },
   { "name": "adc_app", "query": "eric-oss-adc" },
   {
    "name": "adc_podlist",
    "query": "eric-oss-enm-fns.+|eric-oss-sftp-filetrans.+|eric-oss-3gpp-pm-xml-ran.+|eric-oss-4g-pm-event-parser.+|eric-oss-5gpmevt-filetx-proc.+|eric-oss-stats-parser-configurator.+|eric-oss-ves-collector.+|eric-oss-5gpmevt-filetx-proc.*"
   },
   { "name": "adc_datname", "query": ".+" },
   { "name": "adc_domain", "query": "DMI" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/domains/current/data-management-and-ingest/multivendor-adc.html\">Multivendor ADC</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $adc_domain\r\n<br>\r\n<b>App:</b> $adc_app\r\n<br>\r\n<b>Pods:</b> ${adc_podlist}\r\n<br>\r\n<b>Databases:</b> ${adc_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint for $adc_app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $adc_app",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$adc_app'}[$__rate_interval]) ) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $adc_app for $adc_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $adc_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $adc_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$adc_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $adc_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $adc_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "work in progress - % memory of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"})) by (container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"})) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "work in progress - % CPU of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"}[$__rate_interval])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$adc_podlist\",container!~\"\"})/100000) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "$adc_app specific info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Handled",
     "type": "stat",
     "description": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total, eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total,eric_oss_enm_fns:notifications_sent_total",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"})[$__rate_interval]) ",
       "legendFormat": "notifications_sent_total"
      },
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",job!=\"kubernetes-pods\"})[$__rate_interval]) ",
       "legendFormat": "num_output_kafka_messages_produced_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods'})[$__rate_interval]) ",
       "legendFormat": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_5gpmevt_filetx_proc:event_files_processed_total{site=\"$site\"})[$__rate_interval]) ",
       "legendFormat": "eric_oss_5gpmevt_filetx_proc:event_files_processed_total"
      }
     ]
    },
    {
     "title": "ADC Processing",
     "type": "timeseries",
     "description": "notifications_sent_total, num_output_kafka_messages_produced_successfully_total and eric_oss_3gpp_parser_num_parsed_files_total_successfully_total per minute.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"})[$__rate_interval]) ",
       "legendFormat": "notifications_sent_total"
      },
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",job!=\"kubernetes-pods\"})[$__rate_interval]) ",
       "legendFormat": "num_output_kafka_messages_produced_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods'})[$__rate_interval]) ",
       "legendFormat": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_5gpmevt_filetx_proc:event_files_processed_total{site=\"$site\"})[$__rate_interval]) ",
       "legendFormat": "eric_oss_5gpmevt_filetx_proc:event_files_processed_total"
      }
     ]
    },
    {
     "title": "ADC Processing - 9 min sample",
     "type": "timeseries",
     "description": "notifications_sent_total, num_output_kafka_messages_produced_successfully_total and eric_oss_3gpp_parser_num_parsed_files_total_successfully_total per minute.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"})[9m]) ",
       "legendFormat": "eric_oss_enm_fns:notifications_sent_total"
      },
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",job!=\"kubernetes-pods\"})[9m]) ",
       "legendFormat": "eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods'})[9m]) ",
       "legendFormat": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_5gpmevt_filetx_proc:event_files_processed_total{site=\"$site\"})[9m]) ",
       "legendFormat": "eric_oss_5gpmevt_filetx_proc:event_files_processed_total"
      }
     ]
    },
    {
     "title": "ADC Processing - 9 min sample - FNS Notifications",
     "type": "timeseries",
     "description": "notifications_sent_total, num_output_kafka_messages_produced_successfully_total and eric_oss_3gpp_parser_num_parsed_files_total_successfully_total per minute.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"})[9m]) ",
       "legendFormat": "eric_oss_enm_fns:notifications_sent_total"
      }
     ]
    },
    {
     "title": "ADC Processing - 9 min sample - SFTP Files transferred",
     "type": "timeseries",
     "description": "notifications_sent_total, num_output_kafka_messages_produced_successfully_total and eric_oss_3gpp_parser_num_parsed_files_total_successfully_total per minute.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 100 },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",job!=\"kubernetes-pods\"})[9m]) ",
       "legendFormat": "eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total"
      }
     ]
    },
    {
     "title": "ADC Processing - 9 min sample - Files Parsed",
     "type": "timeseries",
     "description": "notifications_sent_total, num_output_kafka_messages_produced_successfully_total and eric_oss_3gpp_parser_num_parsed_files_total_successfully_total per minute.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 100 },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods'})[9m]) ",
       "legendFormat": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total"
      }
     ]
    },
    {
     "title": "ADC Processing Latency",
     "type": "timeseries",
     "description": "Tracks the latency between FNS, SFTP File Transfer and the 3GPP Ran Parser in file processing",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"}[15m])) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",job!=\"kubernetes-pods\"}[15m]))  by (app_kubernetes_io_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods'}[15m]))  by (app_kubernetes_io_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(eric_oss_5gpmevt_filetx_proc:event_files_processed_total{site=\"$site\"}[15m]))  by (app_kubernetes_io_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Number of PM Counter files that failed to be parsed for this time period",
     "type": "stat",
     "description": "eric_oss_3gpp_parser_num_parser_files_failed_total",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parser_files_failed_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of PM Counter files that failed to be parsed",
     "type": "timeseries",
     "description": "sum of eric_oss_3gpp_parser_num_parser_files_failed_total",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eric_oss_3gpp_parser_num_parser_files_failed_total{site=\"$site\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "5G Events files - eric_oss_5gpmevt_filetx_proc:event_files_processed_total",
     "type": "timeseries",
     "description": "eric_oss_5gpmevt_filetx_proc:event_files_processed_total",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eric_oss_5gpmevt_filetx_proc:event_files_processed_total{site=\"$site\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total",
     "type": "stat",
     "description": "eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "5G Events files - eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total",
     "type": "timeseries",
     "description": "eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total{site=\"$site\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ADC - Kafka Producer records Send Rate",
     "type": "timeseries",
     "description": "What, in Volume, is being written to kafka by ADC. kafka_producer_record_send_rate\n\nPM Stats files are being split up into individual records, so one PM stats file may generate between 80 to 200 records.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_producer_record_send_rate{site=\"$site\",app_kubernetes_io_instance=~\"$adc_app\"} ) by (app_kubernetes_io_name) ",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "4G Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "4gpmevent Parser - Rate of PMEventParser dropped files count !! Dropped as in not sent to kafka? !!",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(csm_event_drop_count {site=\"$site\"})[$__rate_interval]) by (app)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent Parser - Rate of of PMEventparser sent file count  !! File set to where - kafka? !!",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(csm_sent_event_count{site=\"$site\"})[$__rate_interval]) by (app)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent Parser - Rate of PMEventParser dropped files count !! Dropped as in not sent to kafka? !!",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(csm_event_drop_count {site=\"$site\"})[$__rate_interval]) by (app)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent Parser - Rate of of PMEventparser receive events from 4g file transfer service ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(csm_received_event_count  {site=\"$site\"})[$__rate_interval]) by (app)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent filetrans microservice - Rate of 4G Events produced for the given 4g input files  - !! Unsure what this means kafka events? !!",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_4gpmevent_filetrans_proc:total_event_produced_successfully_total{site=\"$site\",job!=\"kubernetes-pods\"})[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent filetrans microservice - Rate of 4G Event failed events transfer  !! To 4G Parser?!!",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_4gpmevent_filetrans_proc:num_failed_file_transfer_total  {site=\"$site\",job!=\"kubernetes-pods\"})[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent filetrans microservice - Rate of 4G Event transferred after processing - !! Transferred to where 4G Parser !!!",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_4gpmevent_filetrans_proc:num_successful_file_transfer_total {site=\"$site\",job!=\"kubernetes-pods\"})[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4gpmevent filetrans microservice - Rate of 4G Event files processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_4gpmevent_filetrans_proc:event_files_processed_total {site=\"$site\",job!=\"kubernetes-pods\"})[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "FNS Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "ADC Failed FLS Requests (eric_oss_enm_fns:fls_requests_failed_total)",
     "type": "stat",
     "description": "eric_oss_enm_fns:fls_requests_failed_total",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:fls_requests_failed_total{site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ADC Total Failed FLS Requests for this time period",
     "type": "stat",
     "description": "fls_requests_failed_total",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:fls_requests_failed_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ADC Failed FLS Requests",
     "type": "timeseries",
     "description": "fls_requests_failed_total by topic",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:fls_requests_failed_total{site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "notifications_sent_total",
     "type": "stat",
     "description": "notifications_sent_total by topic",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{job=\"eric-oss-enm-fns\",site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ADC Total Failed FLS Requests for this time period",
     "type": "stat",
     "description": "fls_requests_failed_total",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 108 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{job=\"eric-oss-enm-fns\",site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "notifications_sent_total",
     "type": "timeseries",
     "description": "notifications_sent_total by topic",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{job=\"eric-oss-enm-fns\",site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "kafka_producer_topic_record_send_rate",
     "type": "timeseries",
     "description": "kafka_producer_topic_record_send_rateby topic",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(kafka_producer_topic_record_send_rate{site=\"$site\",app_kubernetes_io_instance=~\"$adc_app\"}) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SFTP Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_oss_sftp_filetrans:processed_counter_file_data_volume_total rate",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:processed_counter_file_data_volume_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_sftp_filetrans:processed_counter_file_data_volume_total{site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "sftp - Rate of Time to Process Counter Files",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:processed_counter_file_time_total_seconds_count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(eric_oss_sftp_filetrans:processed_counter_file_time_total_seconds_count{site=\"$site\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eric_oss_sftp_filetrans:processed_counter_file_data_volume_total",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:processed_counter_file_data_volume_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:processed_counter_file_data_volume_total{site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "sftp - Rate of Time to Process Counter Files",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:processed_counter_file_time_total_seconds_count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_sftp_filetrans:processed_counter_file_time_total_seconds_count{site=\"$site\"}[$__rate_interval])) by (app_kubernetes_io_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eric_oss_sftp_filetrans:num_failed_bdr_uploads_total",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:num_failed_bdr_uploads_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_failed_bdr_uploads_total {site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eric_oss_sftp_filetrans:processed_counter_file_data_volume_total",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:processed_counter_file_data_volume_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_sftp_filetrans:processed_counter_file_data_volume_total{site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eric_oss_sftp_filetrans:num_successful_bdr_uploads_total ",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:num_successful_bdr_uploads_total \n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_successful_bdr_uploads_total {site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{app_kubernetes_io_name}}-rate"
      }
     ]
    },
    {
     "title": "eric_oss_sftp_filetrans:processed_bdr_data_volume_total",
     "type": "timeseries",
     "description": "eric_oss_sftp_filetrans:processed_bdr_data_volume_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_sftp_filetrans:processed_bdr_data_volume_total {site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parser Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_oss_3gpp_parser_num_input_kafka_messages_received_total",
     "type": "timeseries",
     "description": "eric_oss_3gpp_parser_num_input_kafka_messages_received_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_input_kafka_messages_received_total{site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eric_oss_3gpp_parser_num_output_kafka_messages_produced_successfully_total",
     "type": "timeseries",
     "description": "eric_oss_3gpp_parser_num_output_kafka_messages_produced_successfully_total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_output_kafka_messages_produced_successfully_total{site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eric_oss_3gpp_parser_num_successful_bdr_downloads_total",
     "type": "timeseries",
     "description": "eric_oss_3gpp_parser_num_successful_bdr_downloads_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_successful_bdr_downloads_total{site=\"$site\"} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total",
     "type": "timeseries",
     "description": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods'} [$__rate_interval] ) ) by (app_kubernetes_io_name)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}