{
 "title": "EIC App Manager Dashboard",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(eric_oss_enm_fns:notifications_sent_total,site)"
    }
   },
   { "name": "appmgr_app", "query": "eric-oss-app-mgr" },
   {
    "name": "appmgr_podlist",
    "query": "eric-appmgr-data-document-db.*|eric-lcm-container-registry.*|eric-lcm-helm-chart-registry.*|eric-lcm-helm-executor.*|eric-oss-app-lcm.*|eric-oss-app-onboarding.*|job-on-board-main.*|job-decompressor.*|job-parser*|job-push-image.*|job-push-helm.*|eric-lcm-container-registry-registry.*|eric-appmgr-data-document-db.*|eric-lcm-container-registry-bragent.*|eric-lcm-helm-chart-registry-bragent.*"
   },
   { "name": "appmgr_datname", "query": ".+" },
   { "name": "appmgr_domain", "query": "Automation Enablement" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/domains/current/automation-enablement/app-management.html\">App Management</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $appmgr_domain\r\n<br>\r\n<b>App:</b> $appmgr_app\r\n<br>\r\n<b>Pods:</b> ${appmgr_podlist}\r\n<br>\r\n<b>Databases:</b> ${appmgr_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint for $appmgr_app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $appmgr_app",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app'}[$__rate_interval]) ) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $appmgr_app for $appmgr_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $adc_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $adc_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$appmgr_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $adc_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $adc_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "work in progress - % memory of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"})) by (container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"})) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "work in progress - % CPU of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"}[$__rate_interval])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$appmgr_podlist\",container!~\"\"})/100000) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "$appmgr_app specific info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request rate per endpoint for $appmgr_app",
     "type": "timeseries",
     "description": "Average http_server_requests_seconds_sum by URI for $appmgr_app",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app'}[$__rate_interval]) ) by (uri,status,method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Request rate per endpoint for $appmgr_app",
     "type": "timeseries",
     "description": "Average http_server_requests_seconds_sum by URI for $appmgr_app",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app'}[$__rate_interval]) ) by (method,status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "App Life Cycle Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instantiate and Terminate an instance of an App",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/app-instances',method=\"POST\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Instantiate - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      },
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/app-instances/{appInstanceId}',method=\"PUT\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Terminate - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Update an instance of an App",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/app-instances',method=\"PUT\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Instantiate - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Get a list of all instances of every App",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/app-instances',method=\"GET\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "List all instances of every App - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Get a list of all artifacts from an App instance",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/app-instances/{appInstanceId}/artifact-instances',method=\"GET\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Get a list of all artifacts from an App instance - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Delete an instances of an App",
     "type": "timeseries",
     "description": "Delete one or more App instances, and their related artifact instances.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/apps/{appId}/app-instances',method=\"DELETE\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Delete an instances of an App - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Off-board an App",
     "type": "timeseries",
     "description": "Delete an App, this includes the App instance, their related artifact instances, and the App package.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$appmgr_app',uri='/app-lcm/v1/apps/{appId}',method=\"DELETE\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Off-board an App - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "App Onboarding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Onboard an App from a CSAR App Package File",
     "type": "timeseries",
     "description": "Upload a CSAR App package and onboard it.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods',uri='/app-manager/onboarding/v1/apps',method=\"POST\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Onboard - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Get an Onboarded App",
     "type": "timeseries",
     "description": "Get or query a specified App onboarded to App Manager - number of times API is called",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\", method=\"GET\",uri=\"/app-manager/onboarding/v1/apps\",security_istio_io_tlsMode!=\"istio\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Get an Onboarded App - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "Query on this graph - Enable/Disable an Onboarded App - can't differentiate between Enable/Disable",
     "type": "timeseries",
     "description": "Note: Currently can't differentiate between an Enable and a Disable\nUpdate the mode attribute of a fully onboarded App. To Enable/Disable for instantiation/termination",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",uri=~\"/app-manager/onboarding/v1/apps/.*\",method=\"PUT\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Enable/Disable an Onboarded App - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    }
   ]
  }
 ]
}