{
 "title": "EIC DMM Dashboard",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{app_kubernetes_io_instance=\"eric-oss-dmm\"},site)"
    }
   },
   { "name": "dmm_app", "query": "eric-oss-dmm" },
   {
    "name": "dmm_podlist",
    "query": "eric-dmm.+|eric-oss-dmm.+|eric-schema-registry-sr.+|eric-oss-data-catalog.+|eric-dmm-common-db.+|eric-oss-data-collection-controller.*|eric-oss-kf-resource-manager.*"
   },
   { "name": "dmm_datname", "query": ".+dmm.+" },
   { "name": "dmm_mytopics", "query": "dmm-app-eng.+" },
   { "name": "dmm_domain", "query": "DMI" },
   {
    "name": "dmm_containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$dmm_podlist\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/domains/current/data-management-and-ingest/data-management-and-movement.html\">Data Management and Movement</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $dmm_domain\r\n<br>\r\n<b>App:</b> $dmm_app\r\n<br>\r\n<b>Pods:</b> ${dmm_podlist}\r\n<br>\r\n<b>Databases:</b> ${dmm_datname}\r\n<br>\r\n<b>Topics:<b> ${dmm_mytopics}"
   }
  },
  {
   "title": "Request rate per endpoint for $dmm_app",
   "type": "timeseries",
   "description": "http_server_requests_seconds_count\n",
   "gridPos": { "h": 9, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$dmm_app'}[$__rate_interval]) ) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $dmm_app for $dmm_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $dmm_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $dmm_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$dmm_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $dmm_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $dmm_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "work in progress - % CPU of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"}[$__rate_interval])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"})/100000) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "work in progress - % memory of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"})) by (container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$dmm_podlist\",container!~\"\"})) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "$dmm_app specific info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate per method for $dmm_app",
     "type": "timeseries",
     "description": "PUT and POST API requests\n",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$dmm_app'}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request rate per endpoint for $dmm_app",
     "type": "stat",
     "description": "PUT and POST API requests\n",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$dmm_app'}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_fetch_manager_records_consumed_total",
     "type": "timeseries",
     "description": "kafka_consumer_fetch_manager_records_consumed_total\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (increase(kafka_consumer_fetch_manager_records_consumed_total{site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "process_open_fds for $dmm_podlist",
     "type": "timeseries",
     "description": "process_open_fds",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{site=\"$site\",kubernetes_pod_name=~\"$dmm_podlist\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available PVC/Disc space",
     "type": "timeseries",
     "description": "kubelet_volume_stats_available_bytes",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_available_bytes{site=\"$site\", persistentvolumeclaim=~\"data(-[0-9]+)?-eric-oss-dmm-kf-op-sz-kafka-[0-9]+\"}) by (persistentvolumeclaim)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Seconds",
     "type": "timeseries",
     "description": "container_cpu_usage_seconds_total",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",container=\"kafka\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active controller",
     "type": "stat",
     "description": "Indicates whether the broker is active and should always be equals to 1 since there is only one broker at the same time that acts as\ncontroller.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{site=\"$site\",strimzi_io_cluster=\"eric-oss-dmm-kf-op-sz\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Brokers Online",
     "type": "stat",
     "description": "Indicates the number of brokers online (currently set to 3)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_leadercount{site=\"$site\",strimzi_io_cluster=\"eric-oss-dmm-kf-op-sz\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "stat",
     "description": "Indicates if the brokers are unresponsive. If broker goes down, it gives the count",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{site=\"$site\",strimzi_io_cluster=\"eric-oss-dmm-kf-op-sz\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "stat",
     "description": "Indicates if the brokers are unresponsive. If broker goes down, it gives the count",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{site=\"$site\",strimzi_io_cluster=\"eric-oss-dmm-kf-op-sz\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_server_brokertopicmetrics_messagesin_total",
     "type": "timeseries",
     "description": "kafka_server_brokertopicmetrics_messagesin_total\n",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_server_brokertopicmetrics_messagesin_total",
     "type": "stat",
     "description": "kafka_server_brokertopicmetrics_messagesin_total\n",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\"}[$__rate_interval])) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_topic_record_send_total",
     "type": "timeseries",
     "description": "kafka_producer_topic_record_send_total\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum (rate((kafka_producer_topic_record_send_total{site=\"$site\"}[$__rate_interval]))) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_fetch_manager_records_consumed_rate",
     "type": "timeseries",
     "description": "kafka_consumer_fetch_manager_records_consumed_rate\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (kafka_consumer_fetch_manager_records_consumed_rate{site=\"$site\"}) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_server_brokertopicmetrics_totalfetchrequests_total",
     "type": "timeseries",
     "description": "kafka_server_brokertopicmetrics_totalfetchrequests_total\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum (rate((kafka_server_brokertopicmetrics_totalfetchrequests_total{site=\"$site\"}[$__rate_interval]))) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_schema_registry_api_success_count_api_success_count",
     "type": "timeseries",
     "description": "kafka_schema_registry_api_success_count_api_success_count",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_schema_registry_api_success_count_api_success_count{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_consumer_metrics_request_total",
     "type": "timeseries",
     "description": "kafka_consumer_consumer_metrics_request_total",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": " rate(kafka_consumer_consumer_metrics_request_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_consumer_metrics_incoming_byte_total",
     "type": "timeseries",
     "description": "kafka_consumer_consumer_metrics_incoming_byte_total",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": " rate(kafka_consumer_consumer_metrics_incoming_byte_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_consumer_metrics_outgoing_byte_total",
     "type": "timeseries",
     "description": "kafka_consumer_consumer_metrics_outgoing_byte_total",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": " rate(kafka_consumer_consumer_metrics_outgoing_byte_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_producer_metrics_request_total",
     "type": "timeseries",
     "description": "kafka_producer_producer_metrics_request_total",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": " rate(kafka_producer_producer_metrics_request_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_producer_metrics_incoming_byte_total",
     "type": "timeseries",
     "description": "kafka_producer_producer_metrics_incoming_byte_total",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": " rate(kafka_producer_producer_metrics_incoming_byte_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_producer_metrics_outgoing_byte_total",
     "type": "timeseries",
     "description": "kafka_producer_producer_metrics_outgoing_byte_total",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": " rate(kafka_producer_producer_metrics_outgoing_byte_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_producer_metrics_requests_in_flight",
     "type": "timeseries",
     "description": "kafka_producer_producer_metrics_requests_in_flight",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " kafka_producer_producer_metrics_requests_in_flight{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_producer_node_metrics_request_total",
     "type": "timeseries",
     "description": "kafka_producer_producer_node_metrics_request_total",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_producer_node_metrics_request_total{site=\"$site\",app_kubernetes_io_instance=~\"$dmm_app\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_server_brokertopicmetrics_messagesin_total",
     "type": "timeseries",
     "description": "kafka_server_brokertopicmetrics_messagesin_total",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "sum (increase(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\",topic=~\".+\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_connection_count_total",
     "type": "timeseries",
     "description": "kafka_consumer_connection_count_total",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_connection_count_total{site=\"$site\"}) by (app)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_network_requestmetrics_requests_total",
     "type": "timeseries",
     "description": "kafka_network_requestmetrics_requests_total",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requests_total{site=\"$site\"}[$__rate_interval])) by (request)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_network_requestmetrics_requestbytes",
     "type": "timeseries",
     "description": "kafka_network_requestmetrics_requestbytes",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requestbytes{site=\"$site\"}[$__rate_interval])) by (request)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_network_requestmetrics_totaltimems_count",
     "type": "timeseries",
     "description": "kafka_network_requestmetrics_totaltimems_count",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_totaltimems_count{site=\"$site\"}[$__rate_interval])) by (request)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Test Topics $dmm_mytopics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In Per Broker for $dmm_mytopics",
     "type": "timeseries",
     "description": "kafka_server_brokertopicmetrics_messagesin_total",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (increase(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\",topic=~\"$dmm_mytopics\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_log_log_size",
     "type": "timeseries",
     "description": "kafka_log_log_size",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kafka_log_log_size{site=\"$site\",topic=~\"$dmm_mytopics\"}) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_server_brokertopicmetrics_totalfetchrequests_total",
     "type": "timeseries",
     "description": "kafka_server_brokertopicmetrics_totalfetchrequests_total",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (increase(kafka_server_brokertopicmetrics_totalfetchrequests_total{site=\"$site\",topic=~\"$dmm_mytopics\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DCC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Characteristics_subscribe_Metrics_seconds_count",
     "type": "timeseries",
     "description": "Information for number of rApps creating a subscription.\nAn rApp sends the request by sending IDS artifact which may contain multiple subscriptions\n",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(Characteristics_subscribe_Metrics_seconds_count{site=\"$site\"}[$__rate_interval])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request per unsubscribe endpoint ",
     "type": "timeseries",
     "description": "Information for number of rApps making unsubscribe requests\n\n\n",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(Characteristics_unsubscribe_Metrics_seconds_count{site=\"$site\",uri=\"/subscription/v1/{rAppID}\"}[$__rate_interval])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request per update predicate endpoint ",
     "type": "timeseries",
     "description": "Information for number of rApps updating specific subscription predicate values.\n\n\n",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(Characteristics_updatePredicates_Metrics_seconds_count{site=\"$site\",uri=\"/subscription/v1/{rAppID}/{subscriptionName}/predicates\"}[$__rate_interval])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate per GET endpoint ",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(Characteristics_metrics_get_seconds_count{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request rate per POST endpoint ",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 9, "w": 7, "x": 10, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(Characteristics_metrics_post_seconds_count{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request rate per PUT endpoint ",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(Characteristics_metrics_put_seconds_count{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of schemas registered per second",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_schema_registry_registered_count_registered_count{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of schemas retrieved per second",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_schema_registry_jersey_metrics_schemas_get_schemas_request_count{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}