{
 "title": "EIC EAS & CH Dashboard",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(eric_oss_enm_fns:notifications_sent_total,site)"
    }
   },
   { "name": "eas_app", "query": "eric-oss-config-handling" },
   {
    "name": "eas_podlist",
    "query": "eric-oss-enm-notification.+|eric-oss-ncmp-.+|eric-oss-ran-topology-adapter.+|eric-oss-enm-model-adapter.+|eric-eo-enm-adapter.+|eric-oss-enm-discovery-adapter.+|eric-oss-enm-notification-adapter.*|eric-oss-enm-discovery-adapter-database-pg.*|eric-oss-enm-model-adapter-database-pg.*|eric-oss-enm-notification-adapter-database-pg.*"
   },
   { "name": "eas_datname", "query": "cpsdb.*" },
   { "name": "eas_domain", "query": "TIC" },
   {
    "name": "eas_containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$eas_podlist\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/domains/current/topology-inventory-and-configuration/ericsson-adaptation-support.html\">Ericsson Adaptation Support</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $eas_domain\r\n<br>\r\n<b>App:</b> $eas_app\r\n<br>\r\n<b>Pods:</b> ${eas_podlist}\r\n<br>\r\n<b>Databases:</b> ${eas_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint for $eas_app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $eas_app",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$eas_app'}[$__rate_interval]) ) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$eas_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$eas_podlist\",container!~\"\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $eas_app for $eas_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $eas_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$eas_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $eas_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$eas_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $eas_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$eas_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $eas_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$eas_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$eas_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Config-Handling CRUD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CH Throughput of config Read operations [STKPI_008]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",app=\"eric-oss-ncmp\",uri=\"/ncmp/v1/ch/{cm-handle}/data/ds/{datastore-name}\",method=\"GET\",status=\"200\"} [$__rate_interval]))",
       "legendFormat": "CM Read"
      }
     ]
    },
    {
     "title": "CH Throughput of config CUD operations [STKPI_009]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",app=\"eric-oss-ncmp\",uri=\"/ncmp/v1/ch/{cm-handle}/data/ds/{datastore-name}\",status=\"204\",method=\"DELETE\"} [$__rate_interval]))",
       "legendFormat": "CM Delete"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",app=\"eric-oss-ncmp\",uri=\"/ncmp/v1/ch/{cm-handle}/data/ds/{datastore-name}\",status=\"201\",method=\"POST\"} [$__rate_interval]))",
       "legendFormat": "CM Create"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",app=\"eric-oss-ncmp\",uri=\"/ncmp/v1/ch/{cm-handle}/data/ds/{datastore-name}\",status=\"200\",method=\"PATCH\"} [$__rate_interval]))",
       "legendFormat": "CM Update"
      }
     ]
    }
   ]
  },
  {
   "title": "Discovery - not yet working",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CM Discovery ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "subsystem_cmhandle_discovery_success_total{site=\"$site\"}",
       "legendFormat": "Notifications processed"
      }
     ]
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications processed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_propagated_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "Notifications processed"
      }
     ]
    },
    {
     "title": "Notifications processing time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_propagated_processing_time_seconds{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "Notifications processing time"
      }
     ]
    },
    {
     "title": "Notifications received",
     "type": "timeseries",
     "description": "Amount of Notifications that come from ENM.\nEIC does not process all notifications coming from ENM",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_filtered_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "Notifications processed"
      }
     ]
    },
    {
     "title": "Notification processing failures",
     "type": "stat",
     "description": "Count of events that failed to be converted to YANG",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_failed_conversion_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "Notifications processing time"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed - RAN Tolpology Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed CTS CM_HANDLE event total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cts_http_request_datasync_cm_handle_event_total{site=\"$site\",status=\"failed\"}[$__range]) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed CTS CM Topology event total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cts_http_request_datasync_cm_event_total{site=\"$site\",status=\"failed\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed events NCMP all output bulk query",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ncmp_http_request_bulk_query_cm_handle_event_total{site=\"$site\",status=\"failed\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed ncmp_http_request_modules_cm_handle_event_total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ncmp_http_request_modules_cm_handle_event_total{site=\"$site\",status=\"failed\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed TIES CM Topology events",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 13, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ties_produce_cm_event_total{site=\"$site\",status=\"failed\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed TIES CM_HANDLE event",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 17, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ties_produce_cm_handle_event_total{site=\"$site\",status=\"failed\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed TIES Enties & relationships event",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ties_http_request_entities_and_relationship_cm_event_total{site=\"$site\",status=\"failed\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS CM_HANDLE event total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(cts_http_request_datasync_cm_handle_event_total{site=\"$site\"}[$__rate_interval])) by (operation,status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS CM Topology event total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(cts_http_request_datasync_cm_event_total{site=\"$site\"}[$__rate_interval])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "The total number of CM Handle events received by RAN Topology Adapter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ncmp_consume_cm_handle_event_ctsties_total{site=\"$site\"}[$__rate_interval])) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ENM consumed events total  - CTS and TIES",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(increase(enmna_consume_cm_event_cts_total{site=\"$site\"}[$__rate_interval])) by (operation)",
       "legendFormat": "CTS - {{operation}}"
      },
      {
       "expr": "sum(increase(enmna_consume_cm_event_ties_total{site=\"$site\"}[$__rate_interval])) by (operation)",
       "legendFormat": "TIES - {{operation}}"
      }
     ]
    },
    {
     "title": "Total events NCMP all output bulk query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ncmp_http_request_bulk_query_cm_handle_event_total{site=\"$site\"}[$__rate_interval])) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ncmp_http_request_modules_cm_handle_event_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ncmp_http_request_modules_cm_handle_event_total{site=\"$site\"}[$__rate_interval])) by (method,status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TIES CM Topology event total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ties_produce_cm_event_total{site=\"$site\"}[$__rate_interval])) by (operation, status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TIES CM_HANDLE event total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ties_produce_cm_handle_event_total{site=\"$site\"}[$__rate_interval])) by (operation, status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TIES Enties & relationships event total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ties_http_request_entities_and_relationship_cm_event_total{site=\"$site\"}[$__rate_interval])) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed - ENM Model Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "enmma_convertEcimToYang_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_convertEcimToYang_count_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_extractModelZipFiles_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(enmma_extractModelZipFiles_count_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_getModuleResources_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_getModuleResources_count_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_extractData_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_extractData_count_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_convertEcimToYang_duration_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_convertEcimToYang_duration_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_extractModelZipFiles_duration_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_extractModelZipFiles_duration_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_getModuleResources_duration_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_getModuleResources_duration_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_extractData_duration_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_extractData_duration_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_buildModelSet_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_buildModelSet_count_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmma_buildModelSet_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmma_buildModelSet_count_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_gets_total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(cache_gets_total{site=\"$site\"}[$__rate_interval])) by (name,result)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_evictions_total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(cache_evictions_total{site=\"$site\"}[$__rate_interval])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_puts_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(cache_puts_total{site=\"$site\"}[$__rate_interval])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cache_size{site=\"$site\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed - ENM Notification Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "enmna_polling_get_crnt_evt_seconds_active_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_get_crnt_evt_seconds_active_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_get_evt_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_get_evt_seconds_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_payload_processing_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_payload_processing_seconds_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_get_crnt_evt_seconds_duration_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_get_crnt_evt_seconds_duration_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_get_evt_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_get_evt_seconds_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_payload_processing_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_payload_processing_seconds_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_connected_systems_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_connected_systems_seconds_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_yang_conversion_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_yang_conversion_seconds_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_ma_model_crnt_req_seconds_active_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_ma_model_crnt_req_seconds_active_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_connected_systems_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_connected_systems_seconds_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_yang_conversion_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_yang_conversion_seconds_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_ma_model_crnt_req_seconds_duration_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_ma_model_crnt_req_seconds_duration_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_connected_systems_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_connected_systems_seconds_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_retried_polling_tasks_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_retried_polling_tasks_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_failed_conversion_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_failed_conversion_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_connected_systems_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_connected_systems_seconds_sum{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_propagated_total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_propagated_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_evt_propagated_processing_time_seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_evt_propagated_processing_time_seconds{site=\"$site\"})[$__rate_interval])  by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_event_topology_total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_event_topology_total{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}