{
 "title": "EIC Overview",
 "tags": [
  "EIC",
  "Overview",
  "EIC_APP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(pg_up{app=\"eric-cm-mediator-db-pg\"},site)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "description": "For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/index.html\">OSS Portfolio Architecture</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n"
   }
  },
  {
   "title": "HTTP staus per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'.*'}[$__rate_interval]) ) by (status) >0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EIC Max Memory Usage v Limits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (site) (container_memory_working_set_bytes{site=\"$site\",image!=\"\"})",
     "legendFormat": "EIC Max Usage"
    },
    {
     "expr": "sum by (site) (container_spec_memory_limit_bytes{site=\"$site\",image!=\"\"})",
     "legendFormat": "EIC Limits"
    }
   ]
  },
  {
   "title": "EIC Max CPU core millicore Usage v Limits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum by (site) (rate(container_cpu_usage_seconds_total{site=\"$site\",image!=\"\"}[$__rate_interval])))*1000",
     "legendFormat": "EIC Max Usage"
    },
    {
     "expr": "(sum by (site) (container_spec_cpu_quota{site=\"$site\",image!=\"\"}/container_spec_cpu_period{site=\"$site\",image!=\"\"}))*1000",
     "legendFormat": "EIC Limits"
    }
   ]
  },
  {
   "title": " CPU Core second rate",
   "type": "stat",
   "description": "This is the container_cpu_usage_seconds_total rate.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Sum(rate(container_cpu_usage_seconds_total{site=\"$site\",container!~\"\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\".*\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\".*\",container!~\"\"})  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "This is the container_memory_working_set_bytes usage.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{site=\"$site\",container!=\"\"})",
     "legendFormat": "{{pod}} ({{container}})"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "ADC Processing - 1 hour sample",
     "type": "timeseries",
     "description": "notifications_sent_total, num_output_kafka_messages_produced_successfully_total and eric_oss_3gpp_parser_num_parsed_files_total_successfully_total per minute.",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"})[1h]) ",
       "legendFormat": "eric_oss_enm_fns:notifications_sent_total"
      },
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",app_kubernetes_io_managed_by=\"\"})[1h]) ",
       "legendFormat": "eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods',app_kubernetes_io_managed_by=\"\"})[1h]) ",
       "legendFormat": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total"
      }
     ]
    },
    {
     "title": "Total Handled",
     "type": "stat",
     "description": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total, eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total,eric_oss_enm_fns:notifications_sent_total",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:notifications_sent_total{site=\"$site\",topic=\"sftp-filetrans\", sidecar_istio_io_inject=\"true\"})[$__rate_interval]) ",
       "legendFormat": "notifications_sent_total"
      },
      {
       "expr": "sum(increase(eric_oss_sftp_filetrans:num_output_kafka_messages_produced_successfully_total{site=\"$site\",app_kubernetes_io_managed_by=\"Helm\"})[$__rate_interval]) ",
       "legendFormat": "num_output_kafka_messages_produced_successfully_total"
      },
      {
       "expr": "sum(increase(eric_oss_3gpp_parser_num_parsed_files_total_successfully_total{site=\"$site\",job='kubernetes-pods',app_kubernetes_io_managed_by=\"\"})[$__rate_interval]) ",
       "legendFormat": "eric_oss_3gpp_parser_num_parsed_files_total_successfully_total"
      }
     ]
    },
    {
     "title": "Failed FLS",
     "type": "stat",
     "description": "eric_oss_enm_fns:fls_requests_failed_total",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(eric_oss_enm_fns:fls_requests_failed_total{site=\"$site\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DMM Request rate per method",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'eric-oss-dmm'}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "keycloak_client_logins",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(keycloak_client_logins{site=\"$site\"})[$__rate_interval]) by (client_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "enmna_polling_get_evt_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(enmna_polling_get_evt_seconds_count{site=\"$site\"}[$__rate_interval])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eric_oss_cmn_topology_svc_core_http_server_requests_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_cmn_topology_svc_core_http_server_requests_seconds_count{site=\"$site\"}[$__rate_interval])) by (method,outcome)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Instantiate and Terminate an instance of an App",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'eric-oss-app-mgr',uri='/app-lcm/v1/app-instances',method=\"POST\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Instantiate - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      },
      {
       "expr": "sum(increase( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'eric-oss-app-mgr',uri='/app-lcm/v1/app-instances/{appInstanceId}',method=\"PUT\"}[$__rate_interval]) ) by (method,status,uri,outcome)",
       "legendFormat": "Terminate - {{method}} - {{uri}} - Status= {{status}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "prometheus_tsdb_head_series",
     "type": "timeseries",
     "description": "prometheus_tsdb_head_series",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{site=\"$site\"}"
      }
     ]
    },
    {
     "title": "prometheus_engine_query_duration_seconds_sum",
     "type": "timeseries",
     "description": "prometheus_engine_query_duration_seconds_sum",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_engine_query_duration_seconds_sum{site=\"$site\"}[$__rate_interval])) by (slice)"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers & Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Pod CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(20,sum   by (pod)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",container!~\"\"})  * 100))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top container_cpu_cfs_throttled_seconds_total",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",container!~\"\"}[1h])) by (pod))",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Top container_memory_working_set_bytes by pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(container_memory_working_set_bytes{site=\"$site\",container!=\"\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}