{
 "title": "EIC GAS Dashboard",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(eric_adp_gas_light_service_num,site)"
    }
   },
   {
    "name": "gas_app",
    "query": "eric-adp-gui-aggregator-service"
   },
   {
    "name": "gas_podlist",
    "query": "eric-adp-gui-aggregator-service.+"
   },
   { "name": "gas_datname", "query": ".+" },
   { "name": "gas_domain", "query": "Base" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $gas_domain\r\n<br>\r\n<b>App:</b> $gas_app\r\n<br>\r\n<b>Pods:</b> ${gas_podlist}\r\n<br>\r\n<b>Databases:</b> ${gas_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint for $gas_app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $gas_app",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(eric_adp_gas_light_ui_http_requests_total{site=\"$site\"}[$__rate_interval]) ) by (code,endpoint)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $gas_app for $gas_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $adc_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"}[1m])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $adc_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$gas_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $adc_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"}[1m])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $adc_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "work in progress - % memory of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"})) by (container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"})) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "work in progress - % CPU of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"}[1m])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$gas_podlist\",container!~\"\"})/100000) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "$gas_app specific info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GAS API Graphs Content",
     "type": "text",
     "gridPos": { "h": 26, "w": 4, "x": 0, "y": 12 },
     "options": {
      "content": "<br>\r\n<br>\r\n<br>\r\n<br>\r\nThe 2 graphs opposite show information for the following GAS APIs:\r\n\r\n<br>\r\n<br>\r\n<br>\r\n\\\"/ui-meta/v1/apps\\\" API\r\n<br>\r\n\\\"/ui-meta/v1/groups\\\" API\r\n<br>\r\n\\\"/ui-meta/v1/components\\\" API\r\n<br>\r\n\\\"/ui\\\" API\r\n<br>\r\n\\\"/ui-logging/v1/logs\\\" API\r\n<br>\r\n\\\"/gas-internal\\\" API\r\n<br>\r\n\\\"/ui-serve/v1/import-map\\\" API\r\n<br>\r\n\\\"/ui-serve/v1/list-packages\\\" API\r\n<br>\r\n\\\"/ui-serve/v1/static\\\" API"
     }
    },
    {
     "title": "Rate of requests to APIs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 20, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_meta_v1_apps_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_meta_v1_groups_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_meta_v1_components_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_logging_v1_logs_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_gas_internal_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_serve_v1_import_map_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_serve_v1_list_packages_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_serve_v1_static_http_requests_total{site=\"$site\"}[$__rate_interval])) by (endpoint,method,code)",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Rate: Time (in ms) spent in backend with processing requests to the APIs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 20, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_meta_v1_apps_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_meta_v1_groups_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_meta_v1_components_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_logging_v1_logs_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_gas_internal_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_serve_v1_import_map_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_serve_v1_list_packages_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(eric_adp_gas_light_ui_serve_v1_static_http_response_times_total{site=\"$site\"}[$__rate_interval])) by (endpoint, method,code)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GAS UI Detailed Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of Service K8s discovered resources",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_service_num{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total number of Pod K8s discovered resources",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_pod_num{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total number of Endpoint K8s discovered resources",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_endpoint_num{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total user and system CPU time spent in seconds.",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(eric_adp_gas_light_process_cpu_seconds_total{site=\"$site\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Resident memory size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_process_resident_memory_bytes{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "To be Checked -> 'To' date - Start time of the process since unix epoch in seconds",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "${__to:date:seconds} - eric_adp_gas_light_process_start_time_seconds{site=\"$site\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Virtual memory size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_process_virtual_memory_bytes{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "Process heap size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_process_heap_bytes{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "Number of open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_process_open_fds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "Maximum number of open file descriptors",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_process_max_fds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "Lag of event loop in seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The minimum recorded event loop delay",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_min_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The maximum recorded event loop delay",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_max_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The mean of the recorded event loop delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_mean_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The standard deviation of the recorded event loop delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_stddev_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The 50th percentile of the recorded event loop delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_p50_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The 90th percentile of the recorded event loop delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_p90_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The 99th percentile of the recorded event loop delays",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_eventloop_lag_p99_seconds{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "The sum of retry counters of in-progress fetch loops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_sum_of_retry_counters_of_in_progress_fetch_loops{site=\"$site\"}",
       "legendFormat": "{{app}} - {{ instance}} "
      }
     ]
    },
    {
     "title": "Total number of active handles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_active_handles_total{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Sum of Number of active libuv handles grouped by handle type. Every handle type is C++ class name",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (eric_adp_gas_light_nodejs_active_handles{site=\"$site\"}) by (type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of active libuv requests grouped by request type. Every request type is C++ class name",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_active_requests{site=\"$site\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Process heap size used from Node.js in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_heap_size_used_bytes{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Node.js external memory size in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_external_memory_bytes{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Process heap size from Node.js in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_heap_size_total_bytes{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Process heap space size used from Node.js in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(eric_adp_gas_light_nodejs_heap_space_size_used_bytes{site=\"$site\"}) by (space)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process heap space size available from Node.js in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(eric_adp_gas_light_nodejs_heap_space_size_available_bytes{site=\"$site\"})by (space)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process heap space size total from Node.js in bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(eric_adp_gas_light_nodejs_heap_space_size_total_bytes{site=\"$site\"}) by (space)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of eric_adp_gas_light_nodejs_gc_duration_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(eric_adp_gas_light_nodejs_gc_duration_seconds_count{site=\"$site\"}[$__rate_interval])",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Rate of eric_adp_gas_light_nodejs_gc_duration_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(eric_adp_gas_light_nodejs_gc_duration_seconds_bucket{site=\"$site\"}[$__rate_interval])) by (kind,le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of eric_adp_gas_light_http_request_duration_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(eric_adp_gas_light_http_request_duration_seconds_bucket{site=\"$site\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Rate of eric_adp_gas_light_http_request_duration_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(eric_adp_gas_light_http_request_duration_seconds_count{site=\"$site\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Rate of eric_adp_gas_light_nodejs_gc_duration_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(eric_adp_gas_light_nodejs_gc_duration_seconds_sum{site=\"$site\"}[$__rate_interval])",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "eric_adp_gas_light_http_request_duration_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(eric_adp_gas_light_http_request_duration_seconds_sum{site=\"$site\"}) by (status_code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of active requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_active_requests_total{site=\"$site\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Node.js version info",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 121 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eric_adp_gas_light_nodejs_version_info{site=\"$site\"}",
       "legendFormat": "Version {{version}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}