{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "EIC",
  "PLATFORM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(kafka_brokers,site)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_requestqueuetimems{site=\"$site\"}, quantile)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_log_log_size{site=\"$site\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthcheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_preferredreplicaimbalancecount{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Broker network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic!=\"\"}[$__rate_interval]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic!=\"\"}[$__rate_interval]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"}[$__rate_interval])*100",
     "legendFormat": "{{app}} : {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput In/Out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages rate In Per Topic",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_messagesin_total",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages rate In Per Broker",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_messagesin_total",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_messagesin_total",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_messagesin_total",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_messagesin_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Bytes rate Out Per Topic",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_bytesout_total",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes rate In Per Broker",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_bytesout_total",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesout_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Bytes rate In Per Topic",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_bytesin_total",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes rate Out Per Broker",
   "type": "timeseries",
   "description": "kafka_server_brokertopicmetrics_bytesout_total",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesout_total{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Online Partitions",
   "type": "graph",
   "description": "Offline partitions over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "graph",
   "description": "Offline partitions over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{site=\"$site\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "description": "Under replicated partitions over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions{site=\"$site\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "graph",
   "description": "Under min in sync replicas partitions over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{site=\"$site\",app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeeper Request Latency",
   "type": "timeseries",
   "description": "Latency in millseconds for ZooKeeper requests from broker. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{site=\"$site\"}",
     "legendFormat": "{{strimzi_io_pod_name}} : Percentile : ({{quantile}})"
    }
   ]
  },
  {
   "title": "Logs size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 20 Largest Log size per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,kafka_log_log_size{site=\"$site\"})",
     "legendFormat": "{{kubernetes_pod_name}} : {{topic}}"
    }
   ]
  },
  {
   "title": "Log size per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",topic=~\"$topic\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Producer - RequestQueueTimeMs",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isnt large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Produce\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Producer - LocalTimeMs",
   "type": "graph",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Produce\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Producer - RemoteTimeMs",
   "type": "graph",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Produce\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Producer - ResponseQueueTimeMs",
   "type": "graph",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Produce\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Producer - ResponseSendTimeMs",
   "type": "graph",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Produce\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Consumer Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Consumer - RequestQueueTimeMs",
   "type": "graph",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isnt large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Fetch\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Consumer - LocalTimeMs",
   "type": "graph",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Fetch\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Consumer - RemoteTimeMs",
   "type": "graph",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Fetch\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Consumer - ResponseQueueTimeMs",
   "type": "graph",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Fetch\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Consumer - ResponseSendTimeMs",
   "type": "graph",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"Fetch\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Fetch Follower Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "FetchFollower - RequestQueueTimeMs",
   "type": "graph",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isnt large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "FetchFollower - LocalTimeMs",
   "type": "graph",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "FetchFollower - RemoteTimeMs",
   "type": "graph",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "FetchFollower - ResponseQueueTimeMs",
   "type": "graph",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "FetchFollower - ResponseSendTimeMs",
   "type": "graph",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{site=\"$site\",app_kubernetes_io_instance=~\"$instance\",quantile=~\"$percentile\",request=\"FetchFollower\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  }
 ]
}