{
 "title": "EIC PMH",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(pm_stats_query_service_exposed_schemas_gauge,site)"
    }
   },
   {
    "name": "pmh_app",
    "query": "eric-oss-pm-stats-calc-handling|pm-stats-calc-handling"
   },
   {
    "name": "pmh_podlist",
    "query": "eric-oss-pm-stats-calculator-.*|eric-oss-pm-stats-exporter-.*|eric-oss-pm-stats-query-service-.*|eric-pm-kpi-.*"
   },
   { "name": "pmh_datname", "query": ".+" },
   { "name": "pmh_domain", "query": "AIR" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/domains/current/assurance-insights-and-reporting/index.html\">PM Stats Calculation Handling</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $pmh_domain\r\n<br>\r\n<b>App:</b> $pmh_app\r\n<br>\r\n<b>Pods:</b> ${pmh_podlist}\r\n<br>\r\n<b>Databases:</b> ${pmh_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint for $pmh_app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $pmh_app",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_count{site=\"$site\", job=\"kubernetes-pods\", app_kubernetes_io_instance=~\"$pmh_app\"}[$__rate_interval])) by (uri, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $pmh_app for $pmh_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $pmh_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $pmh_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$pmh_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $pmh_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $pmh_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "work in progess - % CPU of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"}[$__rate_interval])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"})/1000000) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "work in progress - % memory of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"})) by (container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$pmh_podlist\",container!~\"\"})) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Calculator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persisted KPI Definitions",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pm_stats_calculator_api_definition_persisted_kpi_count{site=\"$site\"})",
       "legendFormat": "Persisted KPI definitions"
      }
     ]
    },
    {
     "title": "Duration of Submitting KPI Definitions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(pm_stats_calculator_api_definition_post_endpoint_duration_ms_95thpercentile{site=\"$site\"})",
       "legendFormat": "Time"
      }
     ]
    },
    {
     "title": "Total Number of Successful Calculations",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pm_stats_calculator_spark_calculation_end_time_number{execution_group!=\"ON_DEMAND\", calculation_status=\"FINALIZING\", site=\"$site\"})",
       "legendFormat": "Scheduled"
      },
      {
       "expr": "count(pm_stats_calculator_spark_calculation_end_time_number{execution_group=\"ON_DEMAND\", calculation_status=\"FINALIZING\", site=\"$site\"})",
       "legendFormat": "On-Demand"
      }
     ]
    },
    {
     "title": "Number of Failed Calculations",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pm_stats_calculator_spark_calculation_end_time_number{calculation_status=\"FAILED\", site=\"$site\"})",
       "legendFormat": "Scheduled"
      }
     ]
    },
    {
     "title": "Calculations in Queue",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pm_stats_calculator_scheduler_scheduled_calculation_queue_count{site=\"$site\"})",
       "legendFormat": "Scheduled"
      },
      {
       "expr": "max(pm_stats_calculator_scheduler_on_demand_calculation_queue_count{site=\"$site\"})",
       "legendFormat": "On-Demand"
      }
     ]
    },
    {
     "title": "Number of Calculations Done",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "increase(max(pm_stats_calculator_scheduler_persisted_calculations_count{state=~\"FINISHED|FAILED\", site=\"$site\"}) by (state))",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Number of KPIs Calculated",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "increase(max(pm_stats_calculator_scheduler_persisted_calculation_results_number{site=\"$site\"}))",
       "legendFormat": "KPIs calculated"
      }
     ]
    },
    {
     "title": "Duration of Successful Calculations",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count_values without() (\"startTime\", pm_stats_calculator_spark_calculation_end_time_number{calculation_status=\"FINALIZING\", site=\"$site\"} >= $__from <= $__to) + on (calculation_id) group_left() (pm_stats_calculator_spark_calculation_end_time_number{calculation_status=\"FINALIZING\", site=\"$site\"} - 1) - on (calculation_id) group_left() pm_stats_calculator_spark_calculation_start_time_number{site=\"$site\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "pm_stats_calculator_spark_calculation_end_time_number{test=\"test\", site=\"$site\"} # Workaround for a grafana bug (#84232)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "KPI Database Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"pg-data-eric-pm-kpi-data-.*\", site=\"$site\"})",
       "legendFormat": "PVC Capacity"
      },
      {
       "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"pg-data-eric-pm-kpi-data-.*\", site=\"$site\"})",
       "legendFormat": "PVC Size"
      },
      {
       "expr": "max(pg_database_size_bytes{datname=\"kpi_service_db\", site=\"$site\"})",
       "legendFormat": "DB Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Exports",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, pm_stats_exporter_cts_avro_export{site=\"$site\"} >= $__from <= $__to) by (id, table, start, end, instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "pm_stats_exporter_cts_avro_export{test=\"test\", site=\"$site\"} # Workaround for a grafana bug (#84232)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Number of Messages Written to Kafka",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pm_stats_exporter_number_of_records_put_on_kafka_total{site=\"$site\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Reports",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pm_stats_exporter_execution_report_timer_seconds_count{site=\"$site\"})",
       "legendFormat": "Number of Execution Reports"
      },
      {
       "expr": "max(pm_stats_exporter_occurrence_of_table_in_execution_reports_total{site=\"$site\"})",
       "legendFormat": "Number of Tables in Execution Reports"
      },
      {
       "expr": "max(pm_stats_exporter_number_of_kpis_in_execution_reports_total{site=\"$site\"})",
       "legendFormat": "Number of KPIs in Execution Reports"
      }
     ]
    },
    {
     "title": "Number of Messages Written to Kafka",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "increase(sum(pm_stats_exporter_number_of_records_put_on_kafka_total{site=\"$site\"}))",
       "legendFormat": "Messages"
      }
     ]
    },
    {
     "title": "Time Between Arrival of Latest Execution Report and Export",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count_values without() (\"startTime\", topk(1, pm_stats_exporter_cts_avro_export{site=\"$site\"} >= $__from <= $__to) by (id, table, start, end, instance)) + on (id, table, start, end, instance) group_left() topk(1, pm_stats_exporter_cts_avro_export{site=\"$site\"}) by (id, table, start, end, instance) - 1) - on (id) group_left() (topk(1, pm_stats_exporter_exec_arrive{site=\"$site\"}) by (id))",
       "legendFormat": "__auto"
      },
      {
       "expr": "pm_stats_exporter_cts_avro_export{test=\"test\", site=\"$site\"} # Workaround for a grafana bug (#84232)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Taken to Process Execution Report Message",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(pm_stats_exporter_execution_report_timer_seconds_max{site=\"$site\"})",
       "legendFormat": "Processing time"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Exposed Schemas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pm_stats_query_service_exposed_schemas_gauge{site=\"$site\"})",
       "legendFormat": "Exposed schemas"
      }
     ]
    },
    {
     "title": "Total Number of Queries",
     "type": "stat",
     "gridPos": { "h": 5, "w": 13, "x": 4, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pm_stats_query_service_list_tables_timer_seconds_count{site=\"$site\"})",
       "legendFormat": "List Tables"
      },
      {
       "expr": "sum(pm_stats_query_service_executed_listing_queries_counter_total{site=\"$site\"})",
       "legendFormat": "List"
      },
      {
       "expr": "sum(pm_stats_query_service_executed_count_queries_counter_total{site=\"$site\"})",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Total Number of Returned Records",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pm_stats_query_service_records_counter_total{site=\"$site\"})",
       "legendFormat": "Records"
      }
     ]
    },
    {
     "title": "Number of Queries Served",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(pm_stats_query_service_served_queries_counter_total{site=\"$site\"}))",
       "legendFormat": "Queries"
      }
     ]
    },
    {
     "title": "Response Time for Queries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{application=\"Query Service\", uri=\"/**\", site=\"$site\"})",
       "legendFormat": "Response time"
      }
     ]
    }
   ]
  },
  {
   "title": "App Engineering Testing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Between First Calculation Start and Last Calculation End",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((topk(1, sort_desc(pm_stats_calculator_spark_calculation_end_time_number{calculation_status=\"FINALIZING\", site=\"$site\"})) - on() bottomk(1, sort(pm_stats_calculator_spark_calculation_start_time_number{site=\"$site\"}))) / 1000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PM Data Sent to Kafka",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(1, sentData{site=\"$site\", job=\"eric-oss-data-loader\"}) by (batchId, startTime, endTime)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}