{
 "title": "POD Analysis Dashboard",
 "tags": [
  "EIC",
  "PLATFORM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(pg_up{app=\"eric-cm-mediator-db-pg\"},site)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\",pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=\"$pod\",container=\"$container\"}[$__rate_interval])*1000",
       "legendFormat": "Pod:  {{pod}} Container: {{container}}"
      }
     ]
    },
    {
     "title": "Container Max CPU millicore Usage v CPU millicore Limit",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=\"$pod\",container=\"$container\"}[$__rate_interval])*1000",
       "legendFormat": "Max Usage"
      },
      {
       "expr": "(container_spec_cpu_quota{site=\"$site\",pod=\"$pod\",container=\"$container\"}/container_spec_cpu_period{site=\"$site\",pod=\"$pod\",container=\"$container\"})*1000",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=\"$pod\",container=\"$container\"}",
       "legendFormat": "Pod:  {{pod}} Container: {{container}}"
      }
     ]
    },
    {
     "title": "Container Max Memory Usage v Limit",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=\"$pod\",container=\"$container\"}",
       "legendFormat": "Max Usage"
      },
      {
       "expr": "container_spec_memory_limit_bytes{site=\"$site\",pod=\"$pod\",container=\"$container\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container CPU throttling Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=\"$pod\",container=\"$container\"}[$__rate_interval])",
       "legendFormat": "Pod:  {{pod}} Container: {{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_cache{site=\"$site\",pod=\"$pod\",container=\"$container\",name!~\"POD\"}",
       "legendFormat": "Pod:  {{pod}} Container: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{site=\"$site\",pod=\"$pod\",interface=\"eth0\"}[$__rate_interval])",
       "legendFormat": "Pod:{{pod}} transmit bytes"
      },
      {
       "expr": "rate(container_network_receive_bytes_total{site=\"$site\",pod=\"$pod\",interface=\"eth0\"}[$__rate_interval])",
       "legendFormat": "Pod:{{pod}} receive bytes"
      }
     ]
    },
    {
     "title": "POD Network Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_transmit_errors_total{site=\"$site\",pod=\"$pod\",interface=\"eth0\"}[$__rate_interval]",
       "legendFormat": "Pod:{{pod}} transmit errors"
      },
      {
       "expr": "container_network_receive_errors_total{site=\"$site\",pod=\"$pod\",interface=\"eth0\"}[$__rate_interval]",
       "legendFormat": "Pod:{{pod}} receive errors"
      }
     ]
    },
    {
     "title": "Total POD Network Transmit Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_network_transmit_bytes_total{site=\"$site\",interface=\"eth0\"}[$__rate_interval]))",
       "legendFormat": "Total Transmit Bytes"
      }
     ]
    },
    {
     "title": "Total POD Network Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_network_receive_bytes_total{site=\"$site\",interface=\"eth0\"}[$__rate_interval]))",
       "legendFormat": "Total Receive Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Total CPU and Memory ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_cpu_usage_seconds_total{site=\"$site\",image!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max CPU Core Usage v CPU Core Limits",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "(sum by (site) (rate(container_cpu_usage_seconds_total{site=\"$site\",image!=\"\"}[$__rate_interval])))",
       "legendFormat": "Max Usage"
      },
      {
       "expr": "(sum by (site) (container_spec_cpu_quota{site=\"$site\",image!=\"\"}/container_spec_cpu_period{site=\"$site\",image!=\"\"}))",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (site) (container_memory_working_set_bytes{site=\"$site\",image!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Memory Usage v Limits",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (site) (container_memory_working_set_bytes{site=\"$site\",image!=\"\"})",
       "legendFormat": "Max Usage"
      },
      {
       "expr": "sum by (site) (container_spec_memory_limit_bytes{site=\"$site\",image!=\"\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Total Memory per Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",image!=\"\"}",
       "legendFormat": "{{pod}}:{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IOPS and Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total IOPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_fs_writes_total{site=\"$site\",image!=\"\"}[$__rate_interval]))",
       "legendFormat": "writes"
      },
      {
       "expr": "sum by (site) (rate(container_fs_reads_total{site=\"$site\",image!=\"\"}[$__rate_interval]))",
       "legendFormat": "reads"
      }
     ]
    },
    {
     "title": "Total Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_fs_writes_bytes_total{site=\"$site\",image!=\"\"}[$__rate_interval]))",
       "legendFormat": "writes"
      },
      {
       "expr": "sum by (site) (rate(container_fs_reads_bytes_total{site=\"$site\",image!=\"\"}[$__rate_interval]))",
       "legendFormat": "reads"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total PVC Capacity",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{site=\"$site\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Total PVC Capacity Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{site=\"$site\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Total PVC Capacity Available",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_available_bytes{site=\"$site\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVC Capacity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_capacity_bytes{site=\"$site\"} ",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVC % Used ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{site=\"$site\"}/kubelet_volume_stats_capacity_bytes{site=\"$site\"})*100",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVC Bytes Used ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{site=\"$site\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BUR Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "BRO PVC Stats",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bro_volume_stats_capacity_bytes{site=\"$site\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "bro_volume_stats_used_bytes{site=\"$site\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "bro_volume_stats_available_bytes{site=\"$site\"}",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "BRO Persistent Volume Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(bro_volume_stats_used_bytes{site=\"$site\"}/bro_volume_stats_capacity_bytes{site=\"$site\"})*100",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "Number of Registered Agents",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(bro_registered_agents{site=\"$site\"})",
       "legendFormat": "Number of Agents"
      }
     ]
    },
    {
     "title": "PLATFORM Scope Backup File's Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bro_disk_usage_bytes{site=\"$site\",backup_type=\"PLATFORM\"}",
       "legendFormat": "{{backup_type}}"
      }
     ]
    },
    {
     "title": "Number of PLATFORM scope backups stored in BRO",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 5, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "bro_stored_backups{site=\"$site\",backup_type=\"PLATFORM\"}",
       "legendFormat": "{{backup_type}}"
      }
     ]
    }
   ]
  }
 ]
}