{
 "title": "EIC RED Metrics",
 "tags": [
  "PLATFORM",
  "EIC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum,site)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum{site=\"$site\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration per request per URI for $app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $app",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\"}[$__rate_interval]) ) by (uri) / sum(rate(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\"}[$__rate_interval]) ) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average duration per request per URI for $app",
   "type": "stat",
   "description": "Duration per request per URI for $app",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\"}[$__rate_interval]) ) by (uri) / sum(rate(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\"}[$__rate_interval]) ) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Request Duration per endpoint for $app",
   "type": "timeseries",
   "description": "Average duration per request per URI for $app",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(http_server_requests_seconds_max{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\"}[$__rate_interval])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Max Request Duration per endpoint for $app",
   "type": "stat",
   "description": "http_server_requests_seconds_max for $app",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "max(rate(http_server_requests_seconds_max{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\"}[$__rate_interval])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes ",
   "type": "timeseries",
   "description": "http_server_requests_seconds_count by status",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\", uri=~'/actuator/.+|/metrics/.+'}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Codes ",
   "type": "stat",
   "description": "http_server_requests_seconds_count by status",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~\"$app\", uri=~'/actuator/.+|/metrics/.+'}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_count for $app",
   "type": "timeseries",
   "description": "http_server_requests_seconds_count for $app",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\", app_kubernetes_io_instance=~\"$app\"}[$__rate_interval])\t) by (uri)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_count for $app",
   "type": "stat",
   "description": "http_server_requests_seconds_count for $app",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\", app_kubernetes_io_instance=~\"$app\"}[$__rate_interval])\t) by (uri)\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error http_server_requests_seconds_count for $app",
   "type": "timeseries",
   "description": "Error http_server_requests_seconds_count for $app",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",  app_kubernetes_io_instance=~\"$app\" ,status!~'2..',status!~'2..'}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error http_server_requests_seconds_count for $app",
   "type": "stat",
   "description": "Error http_server_requests_seconds_count for $app",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{site=\"$site\",  app_kubernetes_io_instance=~\"$app\" ,status!~'2..',status!~'2..'}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}