{
 "title": "EIC TH Dashboard",
 "tags": [ "EIC_APP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(pg_up{app=\"eric-cm-mediator-db-pg\"},site)"
   },
   { "name": "th_app", "query": "eric-oss-cmn-topology-svc-core" },
   {
    "name": "th_podlist",
    "query": "eric-oss-cmn.+|eric-topology-handling-database-pg.+|eric-oss-jms-svc-amq.+|eric-oss-common-topology.+"
   },
   { "name": "th_datname", "query": "cts.*" },
   { "name": "th_domain", "query": "TIC" },
   {
    "name": "th_containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$th_podlist\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://oss-architecture.seli.wh.rnd.internal.ericsson.com/domains/current/topology-inventory-and-configuration/topology-handling.html\">Topology Handling</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> $th_domain\r\n<br>\r\n<b>App:</b> $th_app\r\n<br>\r\n<b>Pods:</b> ${th_podlist}\r\n<br>\r\n<b>Databases:</b> ${th_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$app'}[$__rate_interval])) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$th_podlist\",container!~\"\"}) / sum(container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$th_podlist\",container!~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $th_app for $th_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Core Usage",
     "type": "timeseries",
     "description": "This is the container_cpu_usage_seconds_total rate per container for pods $th_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$th_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "This is the container_memory_working_set_bytes usage per container for pods $th_podlist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$th_podlist\",container!=\"\"}",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling ",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $th_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$th_podlist\",container!~\"\"}[$__rate_interval])",
       "legendFormat": "{{pod}} ({{container}})"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Percentage",
     "type": "timeseries",
     "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $th_podlist.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$th_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$th_podlist\",container!~\"\"})  * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "work in progress - % CPU of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$th_podlist\",container=~\"$th_containers\"}[$__rate_interval])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$th_podlist\",container=~\"$th_containers\"})/100000) by (container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "$th_app specific info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_oss_cmn_topology_svc_core_http_server_requests_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(eric_oss_cmn_topology_svc_core_http_server_requests_seconds_count{site=\"$site\"}[$__rate_interval])) by (method,outcome)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eric_oss_cmn_topology_svc_core_http_server_requests_seconds_count / eric_oss_cmn_topology_svc_core_http_server_requests_total_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(eric_oss_cmn_topology_svc_core_http_server_requests_total_seconds_count{site=\"$site\"}) / sum(eric_oss_cmn_topology_svc_core_http_server_requests_total_seconds_sum{site=\"$site\"})",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}