{
 "title": "EIC USE Metrics",
 "description": "Has standard variables",
 "tags": [
  "EIC",
  "PLATFORM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(jvm_memory_committed_bytes,site)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(jvm_memory_committed_bytes{site=\"$site\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jvm_memory_committed_bytes - heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\r\nsum(jvm_memory_committed_bytes{site=\"$site\",app_kubernetes_io_instance=~\"$app\", area=\"heap\"}) by (kubernetes_pod_name,kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "jvm_memory_max_bytes - nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods', area='nonheap'}) by (kubernetes_pod_name,kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes - nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods', area='nonheap'}) by (kubernetes_pod_name)",
     "legendFormat": "{{jvm_memory_max_bytes}}"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes - nonheap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods',area=\"nonheap\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "jvm_memory_max_bytes - heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\r\nsum(jvm_memory_max_bytes{site=\"$site\",app_kubernetes_io_instance=~\"$app\", area=\"heap\"}) by (kubernetes_pod_name,kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes - heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\r\nsum(jvm_memory_used_bytes{site=\"$site\",app_kubernetes_io_instance=~\"$app\", area=\"heap\"}) by (kubernetes_pod_name,kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jvm_gc_pause_seconds_sum rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job=\"kubernetes-pods\"}[$__rate_interval])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "jvm_gc_pause_seconds_count rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job=\"kubernetes-pods\"}[$__rate_interval])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "jvm_gc_overhead_percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_gc_overhead_percent{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "system_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "system_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "system_load_average_1m (top)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,system_load_average_1m{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'})",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jvm_threads_live_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "process_cpu_usage - avg_over_time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}[5m])",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_peak_threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_peak_threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "logback_events_total rate (top)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,rate(logback_events_total{site=\"$site\",app_kubernetes_io_instance=~\"$app\", job='kubernetes-pods'}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{instance}}"
    }
   ]
  }
 ]
}