{
 "title": "Generic Pod Analysis Dashboard",
 "tags": [
  "PLATFORM",
  "GENERIC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values({__name__=\"up\",job=~\"kubernetes-cadvisor|kubelet-cadvisor\"},site)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{site=\"$site\",pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% memory of container_spec_memory_limit_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$pod\",container!~\"\"})) by (pod) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$pod\",container!~\"\"})) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% cpu of container_spec_cpu_quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$pod\",container!~\"\"}[$__rate_interval])) by (pod) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$pod\",container!~\"\"})/100000) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% CPU and Memory By Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod % memory of container_spec_memory_limit_bytes $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$pod\",container!~\"\"})) by (pod,container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$pod\",container!~\"\"})) by (pod,container) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$pod % cpu of container_spec_cpu_quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$pod\",container!~\"\"}[$__rate_interval])) by (pod,container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$pod\",container!~\"\"})/100000) by (pod,container) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory By Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod Container CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])*1000",
       "legendFormat": "Pod:  {{pod}} Container: {{container}}"
      }
     ]
    },
    {
     "title": "$pod Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "Pod:  {{pod}} Container: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage By Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{site=\"$site\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "Pod:{{pod}} transmit bytes"
      },
      {
       "expr": "rate(container_network_receive_bytes_total{site=\"$site\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "Pod:{{pod}} receive bytes"
      }
     ]
    },
    {
     "title": "$pod Network Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_transmit_errors_total{site=\"$site\",pod=\"$pod\",interface=\"eth0\"}[$__rate_interval]",
       "legendFormat": "Pod:{{pod}} transmit errors"
      },
      {
       "expr": "container_network_receive_errors_total{site=\"$site\",pod=\"$pod\",interface=\"eth0\"}[$__rate_interval]",
       "legendFormat": "Pod:{{pod}} receive errors"
      }
     ]
    },
    {
     "title": "$pod Network Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_network_receive_bytes_total{site=\"$site\",interface=\"eth0\"}[$__rate_interval]))",
       "legendFormat": "Total Receive Bytes"
      }
     ]
    },
    {
     "title": "$pod Network Transmit Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_network_transmit_bytes_total{site=\"$site\",interface=\"eth0\"}[$__rate_interval]))",
       "legendFormat": "Total Transmit Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Deployment CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (site) (rate(container_cpu_usage_seconds_total{site=\"$site\",image!=\"\"}[$__rate_interval]))*1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max CPU core millicore Usage v Limits",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "(sum by (site) (rate(container_cpu_usage_seconds_total{site=\"$site\",image!=\"\"}[$__rate_interval])))*1000",
       "legendFormat": "Max Usage"
      },
      {
       "expr": "(sum by (site) (container_spec_cpu_quota{site=\"$site\",image!=\"\"}/container_spec_cpu_period{site=\"$site\",image!=\"\"}))*1000",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (site) (container_memory_working_set_bytes{site=\"$site\",image!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Memory Usage v Limits",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (site) (container_memory_working_set_bytes{site=\"$site\",image!=\"\"})",
       "legendFormat": "Max Usage"
      },
      {
       "expr": "sum by (site) (container_spec_memory_limit_bytes{site=\"$site\",image!=\"\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Total Memory per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",image!=\"\"}",
       "legendFormat": "{{pod}}:{{container}}"
      }
     ]
    }
   ]
  }
 ]
}