{
 "title": "Log Transformer",
 "description": "Metrics for Log Transformer",
 "tags": [
  "PLATFORM",
  "GENERIC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(lt_jvm_mem_heap_used,site)"
    }
   },
   { "name": "lt_app", "query": "eric-log-transformer" },
   { "name": "lt_podlist", "query": "eric-log-transformer.*" },
   { "name": "lt_datname", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<a target=\"_blank\" href=\"\">TBA</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/IDUN+Home\">IDUN Home</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://pdu-oss-tools5.seli.wh.rnd.internal.ericsson.com/product_role_matrix_new/#osc\">OSC Product Role Matrix</a>\r\n<br>\r\n<a target=\"_blank\" href=\"https://eteamspace.internal.ericsson.com/display/IDUN/Microservice+Repositories+and+Pipelines\">Microservice Repositories and Pipelines</a>\r\n<hr>\r\n<b>Domain:</b> lt_domain\r\n<br>\r\n<b>App:</b> $lt_app\r\n<br>\r\n<b>Pods:</b> ${lt_podlist}\r\n<br>\r\n<b>Databases:</b> ${lt_datname}"
   }
  },
  {
   "title": "Average Request rate per endpoint for $lt_app",
   "type": "timeseries",
   "description": "Average http_server_requests_seconds_sum by URI for $lt_app",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate( http_server_requests_seconds_count{site=\"$site\",job='kubernetes-pods', app_kubernetes_io_instance=~'$lt_app'}[1m]) ) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU Throttling Percentage",
   "type": "stat",
   "description": "This is the sum of container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"}) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers & Pods for $lt_app for $lt_podlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Container CPU Core Usage",
   "type": "timeseries",
   "description": "This is the container_cpu_usage_seconds_total rate per container for pods $lt_podlist.\n\nThis translates to cpu millisecond used per 1000milliseconds. 1 ms/second = 1 millicore\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"}[1m])",
     "legendFormat": "{{pod}} ({{container}})"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "description": "This is the container_memory_working_set_bytes usage per container for pods $lt_podlist.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{site=\"$site\",pod=~\"$lt_podlist\",container!=\"\"}",
     "legendFormat": "{{pod}} ({{container}})"
    }
   ]
  },
  {
   "title": "Container CPU Throttling ",
   "type": "timeseries",
   "description": "This is the container_cpu_cfs_throttled_seconds_total  per container for pods $lt_podlist. \n\nThis represents the amount of millisceconds per 1000 milliseconds that a container has been throttled",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"}[1m])",
     "legendFormat": "{{pod}} ({{container}})"
    }
   ]
  },
  {
   "title": "Container CPU Throttling Percentage",
   "type": "timeseries",
   "description": "This is the container_cpu_cfs_throttled_periods_total / container_cpu_cfs_periods_total for pods $lt_podlist.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum   by (pod,container)  ((container_cpu_cfs_throttled_periods_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"} / container_cpu_cfs_periods_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"})  * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests & Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "work in progress - % memory of container_spec_cpu_quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((container_memory_working_set_bytes{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"})) by (container) / sum((container_spec_memory_limit_bytes{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"})) by (container) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "work in progress - % CPU of container_spec_cpu_quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"}[1m])) by (container) / sum((container_spec_cpu_quota{site=\"$site\",pod=~\"$lt_podlist\",container!~\"\"})/100000) by (container) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$lt_app specific info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Rate of Logs In",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(lt_events_in{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(lt_events_in_total {site=\"$site\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Logs Filtered",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(lt_events_filtered{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(lt_events_filtered_total{site=\"$site\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Logs Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(lt_events_out {kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(lt_events_out_total{site=\"$site\"}[$__rate_interval])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Out / Logs In",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(lt_events_out{site=\"$site\"}[$__range])) / sum(increase(lt_events_in{site=\"$site\"}[$__range])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(lt_events_out_total{site=\"$site\"}[$__range])) / sum(increase(lt_events_in_total{site=\"$site\"}[$__range])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Logs In",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(lt_events_in_total{site=\"$site\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Logs Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(lt_events_out_total{site=\"$site\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log rate/s",
   "type": "timeseries",
   "description": "Number of logs handled per second, this value is dependent on the environment-specific configuration, but for XL deployments a max total of 4000 logs/s is expected - this is denoted by the red threshold on the graph.\nlt_events_in, lt_events_filtered & lt_events_out should be aligned, and there should be no major discrepancies between the graphed lines.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lt_events_in_total{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])",
     "legendFormat": "IN-{{pod}}"
    },
    {
     "expr": "rate(lt_events_filtered_total{site=\"$site\"}[$__rate_interval])",
     "legendFormat": "FTD-{{pod}}"
    },
    {
     "expr": "rate(lt_events_out_total{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])",
     "legendFormat": "OUT-{{pod}}"
    },
    {
     "expr": "rate(lt_events_in{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])",
     "legendFormat": "IN-{{pod}}"
    },
    {
     "expr": "rate(lt_events_filtered{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])",
     "legendFormat": "FTD-{{pod}}"
    },
    {
     "expr": "rate(lt_events_out{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"}[$__rate_interval])",
     "legendFormat": "OUT-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Events duration",
   "type": "timeseries",
   "description": "The total time it takes to process lt_events_in -> lt_events_filtered -> lt_events_out. When no filters are applied this number should not exceed 500. When for example an exclusion filter is applied, events processing can take up to 1500 milliseconds.\n\nAlert: >1500",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(lt_events_duration_millis{kubernetes_pod_name=~\"$lt_podlist\", site=\"$site\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(lt_events_duration_millis_total{site=\"$site\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Log Throughput Rate",
   "type": "timeseries",
   "description": "The ratio of number of events going in and out of the pipelines. A number higher than 1 often indicates the output destination cannot handle the amount of events coming from Log Transformer.\n\nAlert: >1",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(lt_events_in{kubernetes_pod_name=~\"$lt_podlist\", site=\"$site\"}[$__rate_interval])/rate(lt_events_out{kubernetes_pod_name=~\"$lt_podlist\", site=\"$site\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(lt_events_in_total{site=\"$site\"}[$__rate_interval])/rate(lt_events_out_total{ site=\"$site\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WIP - New graph added - to be checked - rate lt_events_in_total / rate lt_events_out_total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(lt_events_in_total {site=\"$site\"}[$__rate_interval]) / rate(lt_events_out_total{site=\"$site\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "description": "Graph showing in % JVM Memory used.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "lt_jvm_mem_used_heap_percent{ site=\"$site\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory",
   "type": "timeseries",
   "description": "Memory used apart from heap compared to committed bytes apart from heap.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "lt_jvm_mem_nonheap_used{kubernetes_pod_name=~\"$lt_podlist\", site=\"$site\"}",
     "legendFormat": "Used-{{kubernetes_pod_name}}"
    },
    {
     "expr": "lt_jvm_mem_nonheap_committed{site=\"$site\"}",
     "legendFormat": "Committed-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection duration",
   "type": "timeseries",
   "description": "Identify high resource utilization.\n\nAlert: >=300",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(lt_jvm_gc_young_collection_time_in_millis{kubernetes_pod_name=~\"$lt_podlist\", site=\"$site\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(lt_jvm_gc_young_collection_time_in_millis_total{site=\"$site\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "description": "The used JVM heap should not reach the max JVM threshold.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(lt_jvm_mem_heap_max{site=\"$site\"})",
     "legendFormat": "Max Heap"
    },
    {
     "expr": "lt_jvm_mem_heap_used{site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "description": "Total memory used in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "lt_process_mem_bytes{site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pipeline Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Latency",
   "type": "timeseries",
   "description": "A higher number indicates a form of back-pressure.\n\nAlert: >0.25",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lt_pipelines_events_queue_push_duration{site=\"$site\"}[$__rate_interval])/rate(lt_pipelines_events_in{site=\"$site\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "description": "If the queue size reaches the max queue size threshold, this indicates a build of logs within the pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(lt_pipelines_max_queue_size{kubernetes_pod_name=~\"$lt_podlist\",site=\"$site\"})",
     "legendFormat": "Max Size"
    },
    {
     "expr": "lt_pipelines_queue_size{site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}