{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "PLATFORM",
  "GENERIC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "prometheus" },
   { "name": "site", "label": "site", "query": { "query": "label_values(pg_static,site)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_static{site=\"$site\"},instance)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_size_bytes{site=\"$site\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pg_stat_database_blks_read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_read{site=\"$site\"}[1m])) by (datname) >0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "pg_stat_database_xact_commit + pg_stat_database_xact_rollback",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "pg_database_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{site=\"$site\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pg_stat_database_numbackends",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(process_open_fds{instance=~\"$instance\",site=\"$site\",job=~\".*postgres.*\"} ) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "description": "process_cpu_seconds_total",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{site=\"$site\",job=~\".*postgres.*\"}[1m])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{site=\"$site\",job=~\".*postgres.*\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "Resident-{{app_kubernetes_io_instance}}"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{ site=\"$site\",job=~\".*postgres.*\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "Virtual-{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "pg_settings_shared_buffers_bytes",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_shared_buffers_bytes{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "description": "pg_settings_effective_cache_size_bytes",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_effective_cache_size_bytes{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "description": "pg_settings_maintenance_work_mem_bytes",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_maintenance_work_mem_bytes{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "description": "pg_settings_work_mem_bytes",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_work_mem_bytes{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "description": "pg_settings_max_wal_size_bytes",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_wal_size_bytes{instance=~\"$instance\",site=\"$site\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "description": "pg_settings_random_page_cost",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_random_page_cost{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "description": "pg_settings_seq_page_cost",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_seq_page_cost{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "description": "pg_settings_max_worker_processes",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_worker_processes{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "description": "pg_settings_max_parallel_workers",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_parallel_workers{instance=~\"$instance\",site=\"$site\"})"
    }
   ]
  },
  {
   "title": "pg_stat_activity_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state!=\".+idle.+\",site=\"$site\"}[$__rate_interval])) by (state,server)",
     "legendFormat": "{{state}} {{server}}"
    }
   ]
  },
  {
   "title": "pg_stat_activity_count - idle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(rate(pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\",state=~\"idle\"}[$__rate_interval])) by (state,server)",
     "legendFormat": "{{state}} {{server}}"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "sum(irate(pg_stat_bgwriter_buffers_alloc{instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_alloc",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend_fsync{instance=~\"$instance\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_backend_fsync",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend{instance=~\"$host\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "sum(irate(pg_stat_bgwriter_buffers_clean{instance=~\"$host\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_clean",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "sum(irate(pg_stat_bgwriter_buffers_checkpoint{instance=~\"$host\", site=\"$site\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_checkpoint",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}) / (sum(pg_stat_database_blks_hit{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}) + sum(pg_stat_database_blks_read{datname=~\"$datname\", instance=~\"$instance\", site=\"$site\"}))",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "pg_stat_database_tup_updated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "pg_stat_database_xact_commit & pg_stat_database_xact_rollback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])>0) by (server)",
     "legendFormat": "commit {{server}}"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])>0) by (server)",
     "legendFormat": "rollback {{server}}"
    }
   ]
  },
  {
   "title": "pg_stat_database_tup_fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{datname}}-{{server}}"
    }
   ]
  },
  {
   "title": "pg_stat_database_tup_inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "pg_stat_database_tup_deleted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_checkpoint_write_time{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_checkpoint_sync_time{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate (worst)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(10,(pg_stat_database_blks_hit{instance=~\"$instance\", datname=~\"$datname\",site=\"$site\"} / (pg_stat_database_blks_read{instance=~\"$instance\", datname=~\"$datname\",site=\"$site\"} + pg_stat_database_blks_hit{instance=~\"$instance\", datname=~\"$datname\",site=\"$site\"})))",
     "legendFormat": "{{ server}}"
    }
   ]
  },
  {
   "title": "pg_stat_database_tup_returned",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_alloc{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend_fsync{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_checkpoint{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_clean{instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}} conflicts"
    },
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}} deadlocks"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_locks_count{datname=~\"$datname\", instance=~\"$instance\",site=\"$site\"}[$__rate_interval])) by (mode,server)",
     "legendFormat": "{{mode}}-{{server}}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_temp_bytes{instance=~\"$instance\", datname=~\"$datname\",site=\"$site\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "DB Size (Bytes)",
   "type": "graph",
   "description": "Disk space used by the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=~\"$instance\",datname=~\"$datname\",site=\"$site\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}