{
 "title": "Prometheus Overview",
 "description": "Get started faster with Grafana Cloud then easily build these dashboards. https://grafana.com/products/cloud/\nOverview of metrics from Prometheus 2.0.  \nUseful for using prometheus to monitor your prometheus.\nRevisions welcome!",
 "tags": [
  "PLATFORM",
  "GENERIC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(prometheus_tsdb_head_series,site)"
    }
   },
   { "name": "interval" }
  ]
 },
 "panels": [
  {
   "title": "At a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Not up",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (app) (up{site=\"$site\"}<1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime [$__range]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{site=\"$site\"}[$__range]) * 100)"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "timeseries",
   "description": "Total number of time series in prometheus.\n zcat dump.004.gz | wc\n 724277  726416 502133740",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Cloud Native Only",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_memory_working_set_bytes",
     "type": "timeseries",
     "description": "container_memory_working_set_bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{site=\"$site\",pod=~\"eric-pm-server.+\",container!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "eric-pm-server",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",container=\"eric-pm-server\"}",
       "legendFormat": "Usage"
      },
      {
       "expr": "container_spec_memory_limit_bytes{site=\"$site\",container=\"eric-pm-server\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "eric-pm-exporter",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",container=\"eric-pm-exporter\"}",
       "legendFormat": "Usage"
      },
      {
       "expr": "container_spec_memory_limit_bytes{site=\"$site\",container=\"eric-pm-exporter\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "eric-pm-configmap-reload",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{site=\"$site\",container=\"eric-pm-configmap-reload\"}",
       "legendFormat": "Usage"
      },
      {
       "expr": "container_spec_memory_limit_bytes{site=\"$site\",container=\"eric-pm-configmap-reload\"}",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "quick numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Missed Iterations [$__range]",
     "type": "stat",
     "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_evaluator_iterations_missed_total{site=\"$site\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Iterations [$__range]",
     "type": "stat",
     "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_evaluator_iterations_skipped_total{site=\"$site\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Tardy Scrapes [$__range]",
     "type": "stat",
     "description": "Total number of scrapes that hit the sample limit and were rejected.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{site=\"$site\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Reload Failures [$__range]",
     "type": "stat",
     "description": "Number of times the database failed to reload block data from disk.",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{site=\"$site\",}[$__range]))\r\n"
      }
     ]
    },
    {
     "title": "Skipped Scrapes [$__range]",
     "type": "stat",
     "description": "Sum of all skipped scrapes",
     "gridPos": { "h": 7, "w": 3, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{site=\"$site\"}[$__range])) + \r\nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{site=\"$site\"}[$__range])) + \r\nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{site=\"$site\"}[$__range])) + \r\nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{site=\"$site\"}[$__range])) "
      }
     ]
    }
   ]
  },
  {
   "title": "Remote Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "prometheus_remote_storage_samples_total",
     "type": "timeseries",
     "description": "prometheus_remote_storage_samples_total",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "increase(prometheus_remote_storage_samples_total{site=\"$site\"}[1m])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "prometheus_remote_storage_samples_pending",
     "type": "timeseries",
     "description": "prometheus_remote_storage_samples_pending",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
     "targets": [
      {
       "expr": "increase(prometheus_remote_storage_samples_pending{site=\"$site\"}[1m])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "prometheus_remote_storage_samples_failed_total",
     "type": "timeseries",
     "description": "prometheus_remote_storage_samples_failed_total",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "increase(prometheus_remote_storage_samples_failed_total{site=\"$site\"}[1m])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "prometheus_remote_storage_samples_retried_total",
     "type": "timeseries",
     "description": "prometheus_remote_storage_samples_retried_total",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
     "targets": [
      {
       "expr": "increase(prometheus_remote_storage_samples_retried_total{site=\"$site\"}[1m])",
       "legendFormat": "{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 scrape_samples_scraped by app,job",
     "type": "timeseries",
     "description": " zcat dump.004.gz | grep -c  \"kubelet-cadvisor\"\n295014",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20,sum by (app,job) (scrape_samples_scraped{site=\"$site\"} ))",
       "legendFormat": "__auto"
      },
      { "legendFormat": "Missed Iterations" }
     ]
    },
    {
     "title": "scrape_samples_scraped by job",
     "type": "piechart",
     "description": "scrape_samples_scraped",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (job) (last_over_time(scrape_samples_scraped{site=\"$site\"}[5m]))",
       "legendFormat": "{{app,job}}"
      }
     ]
    },
    {
     "title": "prometheus_http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "increase(prometheus_http_requests_total{job=\"prometheus\",site=\"$site\"}[$__rate_interval])",
       "legendFormat": "{{code}}-{{handler}}"
      }
     ]
    },
    {
     "title": "prometheus_tsdb_checkpoint_creations_total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_creations_total{job=\"prometheus\",site=\"$site\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Failures and Errors",
     "type": "timeseries",
     "description": "All non-zero failures and errors",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "Failed Connections"
      },
      {
       "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "Missed Iterations"
      },
      {
       "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "Skipped Iterations"
      },
      {
       "expr": "sum(increase(prometheus_rule_evaluation_failures_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "Evaluation"
      },
      {
       "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "Azure Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "Consul RPC"
      },
      {
       "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{site=\"$site\"}[$__rate_interval])) > 0",
       "legendFormat": "DNS Lookup"
      },
      {
       "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "EC2 Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "GCE Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Marathon Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Openstack Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Triton Refresh"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Sample Limit"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Duplicate Timestamp"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Sample Out of Order"
      },
      {
       "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Zookeeper"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "TSDB Compactions"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{site=\"$site\"}[5m])) > 0",
       "legendFormat": "Reload"
      }
     ]
    }
   ]
  },
  {
   "title": "up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Upness (stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "up{site=\"$site\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Storage Memory Chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{site=\"$site\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Series Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{site=\"$site\"}"
      }
     ]
    },
    {
     "title": "Series Created / Removed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_head_series_created_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "prometheus_tsdb_head_series_created_total"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_head_series_removed_total{site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "prometheus_tsdb_head_series_removed_total"
      }
     ]
    }
   ]
  },
  {
   "title": "appended samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Appended Samples per Second",
     "type": "timeseries",
     "description": "Rate of total number of appended samples",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{site=\"$site\"}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrape Sync Total",
     "type": "timeseries",
     "description": "Total number of syncs that were executed on a scrape pool.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_target_scrape_pool_sync_total{site=\"$site\"}) by (scrape_job)"
      }
     ]
    },
    {
     "title": "prometheus_target_sync_length_seconds_sum",
     "type": "timeseries",
     "description": "Actual interval to sync the scrape pool.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{site=\"$site\"}[2m])) by (scrape_job) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "scrapes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,scrape_duration_seconds{site=\"$site\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "timeseries",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{site=\"$site\"})"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{site=\"$site\"})"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{site=\"$site\"})"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{site=\"$site\"})"
    }
   ]
  },
  {
   "title": "durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Rule Evaluation Duration",
     "type": "timeseries",
     "description": "The duration of rule group evaluations",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(1000 * rate(prometheus_evaluator_duration_seconds_sum{site=\"$site\"}[5m])) / rate(prometheus_evaluator_duration_seconds_count{site=\"$site\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_microseconds_count{site=\"$site\"}[1m])) by (handler) > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Prometheus Engine Query Duration Seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_engine_query_duration_seconds_sum{site=\"$site\"}) by (slice)"
      }
     ]
    },
    {
     "title": "Rule Evaluator Iterations",
     "type": "timeseries",
     "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_total{site=\"$site\"}[5m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_missed_total{site=\"$site\"}[5m]))",
       "legendFormat": "Missed"
      },
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_skipped_total{site=\"$site\"}[5m]))",
       "legendFormat": "Skipped"
      }
     ]
    }
   ]
  },
  {
   "title": "notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notifications Sent rate/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_notifications_sent_total{site=\"$site\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "prometheus_rule_evaluation_duration_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{site=\"$site\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Minutes Since Successful Config Reload",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{site=\"$site\"}) / 60",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Successful Config Reload",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_config_last_reload_successful{site=\"$site\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}