{
 "title": "Search Engine",
 "description": "ElasticSearch cluster stats.\r\n\r\nRevision 1 of this dashboard is the same as the Infinity Dashboard Revision 4 (https://grafana.com/dashboards/2322)\r\n\r\nThis is a cleaned up copy with all control characters removed from the dashboard file.  When downloading version 4 of the original Infinity elasticsearch dashboard via curl, the resulting file is corrupted with a missing final curly brace.\r\n",
 "tags": [
  "GENERIC",
  "PLATFORM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status, site)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "\"elasticsearch\""
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{site=\"$site\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(elasticsearch_cluster_health_status{instance=~\"$instance\", color=\"red\", site=\"$site\"}) * 100) + (sum(elasticsearch_cluster_health_status{instance=~\"$instance\", color=\"yellow\", site=\"$site\"}) * 10) + (sum(elasticsearch_cluster_health_status{instance=~\"$instance\", color=\"green\", site=\"$site\"}) * 1)"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{instance=~\"$instance\", site=\"$site\"} > 0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_process_cpu_percent{instance=~\"$instance\", site=\"$site\"}) / count(elasticsearch_process_cpu_percent{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\", site=\"$site\"}) / sum(elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\", site=\"$site\"})) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_number_of_nodes{site=\"$site\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_number_of_data_nodes{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_process_open_files_count{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_active_primary_shards{site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_active_shards{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_relocating_shards{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "singlestat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_delayed_unassigned_shards{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_unassigned_shards{instance=~\"$instance\", site=\"$site\"})"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{site=\"$site\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{instance=~\"$instance\", site=\"$site\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total translog operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_operations{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total translog size in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_size_in_bytes{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tripped for breakers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_breakers_tripped{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}: {{breaker}}"
      }
     ]
    },
    {
     "title": "Estimated size in bytes of breaker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_breakers_estimated_size_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}: {{breaker}}"
      },
      {
       "expr": "elasticsearch_breakers_limit_size_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}: limit for {{breaker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load average",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_os_load1{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "load1: {{name}}"
      },
      {
       "expr": "elasticsearch_os_load5{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "load5: {{name}}"
      },
      {
       "expr": "elasticsearch_os_load15{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "load15: {{name}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_cpu_percent{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "JVM memory usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}} used: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}} max: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}} peak used pool: {{pool}}"
      }
     ]
    },
    {
     "title": "JVM memory committed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_committed_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}} committed: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}} max: {{area}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "1 - (elasticsearch_filesystem_data_available_bytes{instance=~\"$instance\", site=\"$site\"} / elasticsearch_filesystem_data_size_bytes{instance=~\"$instance\", site=\"$site\"})",
       "legendFormat": "{{name}}: {{path}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/sec" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: sent "
      },
      {
       "expr": "0 - irate(elasticsearch_transport_rx_size_bytes_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: received"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents count on node",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents indexed rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "index calls/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents deleted rate",
     "type": "graph",
     "description": "Count of deleted documents on this node",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_docs_deleted{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents merged rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_docs_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents merged bytes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merging time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Throttle time for index store",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Operations  rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "rate(elasticsearch_indices_search_query_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "rate(elasticsearch_indices_merges_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "rate(elasticsearch_indices_refresh_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "rate(elasticsearch_indices_flush_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "rate(elasticsearch_indices_get_exists_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "rate(elasticsearch_indices_get_missing_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "rate(elasticsearch_indices_get_tota{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get"
      },
      {
       "expr": "rate(elasticsearch_indices_indexing_delete_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: indexing_delete"
      }
     ]
    },
    {
     "title": "Total Operations time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "irate(elasticsearch_indices_flush_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "irate(elasticsearch_indices_get_exists_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get_time"
      },
      {
       "expr": "irate(elasticsearch_indices_get_missing_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: indexing_delete"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: get"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations rejected",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_thread_pool_rejected_count{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations queued",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_thread_pool_active_count{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_thread_pool_active_count{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 18, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_thread_pool_completed_count{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field data memory size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_fielddata_evictions{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_query_cache_evictions{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Evictions from filter cache",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_filter_cache_evictions{instance=~\"$instance\", site=\"$site\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of index segments",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_count{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current memory size of segments in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_memory_bytes{instance=~\"$instance\", site=\"$site\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}