{
 "title": "CAPI metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": {
     "query": "label_values(workqueue_work_duration_seconds_count, site)"
    }
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "controller_provider",
    "query": {
     "query": "label_values(workqueue_work_duration_seconds_count{site=\"$site\"},cluster_x_k8s_io_provider)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$controller_provider queued count",
   "type": "timeseries",
   "description": "Shows the number of queued tasks on the Cluster API manager specified from controller_provider.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(workqueue_queue_duration_seconds_count{name=\"cluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} $controller_provider queue count"
    },
    {
     "expr": "increase(workqueue_queue_duration_seconds_count{name=\"azurecluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} $controller_provider queue count"
    },
    {
     "expr": "increase(workqueue_queue_duration_seconds_count{name=\"kubeadmconfig\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} $controller_provider queue count"
    },
    {
     "expr": "increase(workqueue_queue_duration_seconds_count{name=\"awscluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} $controller_provider queue count"
    },
    {
     "expr": "increase(workqueue_queue_duration_seconds_count{name=\"kubeadmcontrolplane\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} $controller_provider queue count"
    }
   ]
  },
  {
   "title": "$controller_provider error count",
   "type": "timeseries",
   "description": "Shows the number of reconciliation errors per controller.  Each controller can be selected from the controller_provider option.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"cluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "$controller_provider queue count"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"azurecluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "$controller_provider queue count"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"kubeadmconfig\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "$controller_provider queue count"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"awscluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "$controller_provider queue count"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"kubeadmcontrolplane\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "$controller_provider queue count"
    }
   ]
  },
  {
   "title": "$controller_provider working task count",
   "type": "timeseries",
   "description": "Shows the number of tasks running per controller at a point in time.  Each controller can be selected from the controller_provider option.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(workqueue_work_duration_seconds_count{name=\"cluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{cluster_x_k8s_io_provider}} {{control_plane}} work count"
    },
    {
     "expr": "increase(workqueue_work_duration_seconds_count{name=\"azurecluster\", site=\"$site\",  cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} {{control_plane}} work count"
    },
    {
     "expr": "increase(workqueue_work_duration_seconds_count{name=\"cluster\", site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{cluster_x_k8s_io_provider}} {{control_plane}} work count"
    },
    {
     "expr": "increase(workqueue_work_duration_seconds_count{name=\"awscluster\", site=\"$site\",  cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "{{name}} {{control_plane}} work count"
    },
    {
     "expr": "increase(workqueue_work_duration_seconds_count{name=\"kubeadmconfig\", site=\"$site\",  cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(workqueue_work_duration_seconds_count{name=\"kubeadmcontrolplane\", site=\"$site\",  cluster_x_k8s_io_provider=\"$controller_provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cert Manager certificates and expiration",
   "type": "table",
   "description": "Lists the certificates managed by CLM and their expiration date.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "certmanager_certificate_expiration_timestamp_seconds{site=\"$site\", name=\"capa-serving-cert\"} * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$controller_provider Queued Tasks Heatmap",
   "type": "heatmap",
   "description": "A heatmap of the Tasks queued on each Cluster controller.\nPeriod of time: The amount of time a task is queued.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(workqueue_queue_duration_seconds_bucket{site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"}[5m])) by(le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$controller_provider Completed Tasks Heatmap",
   "type": "heatmap",
   "description": "A heatmap of the Tasks are executed on each Cluster controller.\nPeriod of time: The amount of time a task is queued.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(workqueue_work_duration_seconds_bucket{site=\"$site\", cluster_x_k8s_io_provider=\"$controller_provider\"})) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}