{
 "title": "Ceph - Pools",
 "description": "Ceph Pools dashboard.",
 "tags": [
  "ceph",
  "pools"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(ceph_health_status, site)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(ceph_pool_metadata, name)"
    }
   },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Pool: $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{site=\"$site\"} * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Available - {{ name }}"
    },
    {
     "expr": "sum(ceph_pool_stored{site=\"$site\"} * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Stored - {{ name }}"
    },
    {
     "expr": "sum(ceph_pool_stored_raw{site=\"$site\"} * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Raw - {{ name }}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((ceph_pool_stored{site=\"$site\"} / (ceph_pool_stored{site=\"$site\"} + ceph_pool_max_avail{site=\"$site\"})) * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) without (instance, pool_id, name)"
    }
   ]
  },
  { "title": "Pool Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Objects in Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{site=\"$site\"} * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Objects - {{ name }}"
    },
    {
     "expr": "sum(ceph_pool_dirty{site=\"$site\"} * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Dirty Objects - {{ name }}"
    },
    {
     "expr": "sum(ceph_pool_quota_objects{site=\"$site\"} * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Quota Objects - {{ name }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd{site=\"$site\"}[3m]) * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Read - {{ name }}"
    },
    {
     "expr": "sum(irate(ceph_pool_wr{site=\"$site\"}[3m]) * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Write - {{ name }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes{site=\"$site\"}[5m]) * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Read Bytes - {{ name }}"
    },
    {
     "expr": "sum(irate(ceph_pool_wr_bytes{site=\"$site\"}[5m]) * on (pool_id) group_left (name) ceph_pool_metadata{name=~\"^$pool$\", site=\"$site\"}) by (name)",
     "legendFormat": "Written Bytes - {{ name }}"
    }
   ]
  }
 ]
}