{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(ceph_health_status, site)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_health_status{site=\"$site\"}) without (instance)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{site=\"$site\"}[5m])) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{site=\"$site\"}[5m])) without (ceph_daemon, instance)"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{site=\"$site\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((ceph_cluster_total_bytes{site=\"$site\"} - ceph_cluster_total_used_bytes{site=\"$site\"}) / ceph_cluster_total_bytes{site=\"$site\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{site=\"$site\"}) without (instance, pool_id)"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_w_in_bytes{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_r_out_bytes{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname=~\"^CephCluster.*\", site=\"$site\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{site=\"$site\"}[5m])) without (ceph_daemon, instance)"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{site=\"$site\"}[5m])) without (ceph_daemon, instance)"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{site=\"$site\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_num_sessions{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{site=\"$site\"}) without (instance, ceph_daemon) - count(ceph_osd_in{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{site=\"$site\"} == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{site=\"$site\"}) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(ceph_osd_op_w_latency_sum{site=\"$site\"}[5m]) / rate(ceph_osd_op_w_latency_count{site=\"$site\"}[5m])) >= 0) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Avg  Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(ceph_osd_op_r_latency_sum{site=\"$site\"}[5m]) / rate(ceph_osd_op_r_latency_count{site=\"$site\"}[5m])) >= 0) without (instance, ceph_daemon)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts from CephThanos",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\", site=\"$site\"}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "topk(5, sort_desc(ceph_osd_apply_latency_ms{site=\"$site\"} + ceph_osd_commit_latency_ms{site=\"$site\"}))"
      }
     ]
    },
    {
     "title": "Down OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "ceph_osd_up{site=\"$site\"} == 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(ceph_osd_metadata{site=\"$site\"}) by (ceph_version)",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(ceph_mon_metadata{site=\"$site\"}) by (ceph_version)",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(ceph_mds_metadata{site=\"$site\"}) by (ceph_version)",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(ceph_rgw_metadata{site=\"$site\"}) by (ceph_version)",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{site=\"$site\"}) without (instance)",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "sum(ceph_cluster_total_bytes{site=\"$site\"} - ceph_cluster_total_used_bytes{site=\"$site\"}) without (instance)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(ceph_cluster_total_used_bytes{site=\"$site\"}) without (instance)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{site=\"$site\"}[5m])) without (instance, ceph_daemon)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{site=\"$site\"}[5m])) without (instance, ceph_daemon)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{site=\"$site\"}[5m])) without (instance, ceph_daemon)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{site=\"$site\"}[5m])) without (instance, ceph_daemon)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Bytes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_num_bytes_recovered{site=\"$site\"} * on (instance, pool_id) group_left (name) ceph_pool_metadata{site=\"$site\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_num_objects_recovered{site=\"$site\"} * on (instance, pool_id) group_left (name) ceph_pool_metadata{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{site=\"$site\"} * on (instance, pool_id) group_left (name) ceph_pool_metadata{site=\"$site\"}) without (instance)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_quota_bytes{site=\"$site\"} * on (instance, pool_id) group_left (name) ceph_pool_metadata{site=\"$site\"}) without (instance)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_quota_objects{site=\"$site\"}) without (instance) * on (instance, pool_id) group_left (name) ceph_pool_metadata{site=\"$site\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OSD Type Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ceph_bluestore_commit_lat_count{site=\"$site\"}) without (instance, ceph_daemon)",
     "legendFormat": "BlueStore"
    },
    {
     "expr": "count(ceph_filestore_journal_latency_count{site=\"$site\"}) without (instance, ceph_daemon)",
     "legendFormat": "FileStore"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_active{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_inconsistent{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{site=\"$site\"}) without (instance, pool_id)",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{site=\"$site\"}[$__rate_interval])) without (instance, ceph_daemon)",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "(rate(ceph_osd_op_r_latency_sum{site=\"$site\"}[5m]) / rate(ceph_osd_op_r_latency_count{site=\"$site\"}[5m])) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "(rate(ceph_osd_op_w_latency_sum{site=\"$site\"}[5m]) / rate(ceph_osd_op_w_latency_count{site=\"$site\"}[5m])) >= 0"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(ceph_osd_op_r_latency_sum{site=\"$site\"}[5m]) / rate(ceph_osd_op_r_latency_count{site=\"$site\"}[5m])) >= 0) without (instance, ceph_daemon)",
     "legendFormat": "read"
    },
    {
     "expr": "avg((rate(ceph_osd_op_w_latency_sum{site=\"$site\"}[5m]) / rate(ceph_osd_op_w_latency_count{site=\"$site\"}[5m])) >= 0) without (instance, ceph_daemon)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{site=\"$site\"}) without (instance, ceph_daemon)",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{site=\"$site\"}) without (instance, ceph_daemon)",
     "legendFormat": "commit"
    }
   ]
  },
  { "title": "Node Statistics (NodeExporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{site=\"$site\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(node_memory_Active_anon_bytes{site=\"$site\"}) without (instance)",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode!=\"idle\", site=\"$site\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{site=\"$site\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total{site=\"$site\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{mountpoint=\"/\", device!=\"rootfs\", site=\"$site\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\", device!=\"rootfs\", site=\"$site\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}