{
 "title": "ENM Overview",
 "tags": [
  "Overview",
  "ENM_APP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(jboss_dh_com_dt_ericsson_dt_oss_dt_services_dt_pm_dt_collection_dt_instrumentation_dt_pm_dh_service_cl_type_eq_FileCollectionStatistics_nm_combinedNumberOfFilesCollected,site)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "alarmCountReceivedByAPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(jboss_dh_com_dt_ericsson_dt_oss_dt_services_dt_fm_dt_alarmprocessor_dt_instrumentation_dt_AlarmProcessor_cl_type_eq_APSInstrumentedBean_nm_alarmCountReceivedByAPS{site=\"$site\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "alarmCountReceivedByAPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(jboss_dh_com_dt_ericsson_dt_oss_dt_services_dt_fm_dt_alarmprocessor_dt_instrumentation_dt_AlarmProcessor_cl_type_eq_APSInstrumentedBean_nm_alarmCountReceivedByAPS{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "SupervisedNodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_APG_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) ",
     "legendFormat": "APG"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_SNMP_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) ",
     "legendFormat": "SNMP"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_COM_dh_ECIM_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"})",
     "legendFormat": "ECIM"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_cm_dh_router_dh_policy_cl_type_eq_SupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"})",
     "legendFormat": "CPP"
    }
   ]
  },
  {
   "title": "Unsynced Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_APG_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - min(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_APG_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"}) ",
     "legendFormat": "APG"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_SNMP_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - min(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_SNMP_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"}) ",
     "legendFormat": "SNMP"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_COM_dh_ECIM_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - min(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_COM_dh_ECIM_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"})",
     "legendFormat": "ECIM"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_cm_dh_router_dh_policy_cl_type_eq_SupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_cm_dh_router_dh_policy_cl_type_eq_SupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"})",
     "legendFormat": "CPP"
    }
   ]
  },
  {
   "title": "combinedNumberOfFilesCollected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(jboss_dh_com_dt_ericsson_dt_oss_dt_services_dt_pm_dt_collection_dt_instrumentation_dt_pm_dh_service_cl_type_eq_FileCollectionStatistics_nm_combinedNumberOfFilesCollected{site=\"$site\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "combinedNumberOfFilesCollected",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(jboss_dh_com_dt_ericsson_dt_oss_dt_services_dt_pm_dt_collection_dt_instrumentation_dt_pm_dh_service_cl_type_eq_FileCollectionStatistics_nm_combinedNumberOfFilesCollected{site=\"$site\"}[$__rate_interval])) ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "jboss_dh_JmsQueue_dh_ComEcimMdbNotificationListener_0_nm_messagesAdded (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_JmsQueue_dh_ComEcimMdbNotificationListener_0_nm_messagesAdded{site=\"$site\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jboss_dh_JmsQueue_dh_ComEcimMdbNotificationListener_0_nm_messagesAdded",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_JmsQueue_dh_ComEcimMdbNotificationListener_0_nm_messagesAdded{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- (sum by(instance) (irate(node_cpu_seconds_total{site=\"$site\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{site=\"$site\"}[$__rate_interval]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}