{
 "title": "Infrastructure Monitoring - Compact",
 "tags": [
  "PLATFORM",
  "ENM"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_handlers_dt_utility_dt_instrumentation_dt_com_dh_ecim_dh_notification_dh_supervision_dh_handler_cl_type_eq_ComEcimNotificationInstrumentation_nm_totalBufferedNotifications,site)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress Network bandwidth issue count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time((count_over_time((sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesBytesTransfered{site=\"$site\"}[$__rate_interval]))/(sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesTransferTime{site=\"$site\"}[$__rate_interval])/1000))  <1000000)[10m:1m])>9)[$__range])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "mspmPullFilesBytesTransferedBandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time((sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesBytesTransfered{site=\"$site\"}[$__rate_interval]))/(sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesTransferTime{site=\"$site\"}[$__rate_interval])/1000))  <1000000)[10m:1m])>9\r\n",
     "legendFormat": "Bandwidth problem indicator"
    },
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesBytesTransfered{site=\"$site\"}[$__rate_interval]))/(sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesTransferTime{site=\"$site\"}[$__rate_interval])/1000))",
     "legendFormat": "Bandwidth"
    }
   ]
  },
  {
   "title": "mspmPullFilesWriteBandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesBytesStoredFS{site=\"$site\"}[$__rate_interval]))/(sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesWriteTimeFS{site=\"$site\"}[$__rate_interval])/1000)))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unsynced Nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_APG_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - min(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_APG_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"}) ",
     "legendFormat": "APG"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_SNMP_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - min(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_SNMP_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"}) ",
     "legendFormat": "SNMP"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_COM_dh_ECIM_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - min(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_COM_dh_ECIM_dh_CM_dh_ROUTER_dh_POLICY_cl_type_eq_DefaultSupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"})",
     "legendFormat": "ECIM"
    },
    {
     "expr": "max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_cm_dh_router_dh_policy_cl_type_eq_SupervisionInstrumentation_nm_numberOfSupervisedNodes{site=\"$site\"}) - max(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_cm_dt_router_dt_policy_dt_instrumentation_dt_cm_dh_router_dh_policy_cl_type_eq_SupervisionInstrumentation_nm_numberOfSynchronizedNodes{site=\"$site\"})",
     "legendFormat": "CPP"
    }
   ]
  },
  {
   "title": "mspmPullFilesSessionCreationTime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesSessionCreationTime{site=\"$site\"}[$__rate_interval]))  >0",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "mspmPullFilesWriteTimeFS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesWriteTimeFS{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "jboss_dh_JmsQueue_dh_ComEcimMdbNotificationListener_0_nm_messagesAdded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_JmsQueue_dh_ComEcimMdbNotificationListener_0_nm_messagesAdded{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "mspmPullFilesBytesTransfered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesBytesTransfered{site=\"$site\"}[$__rate_interval]))  >0",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "mspmPullFilesBytesStoredFS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesBytesStoredFS{site=\"$site\"}[$__rate_interval])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "totalBufferedNotifications",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_handlers_dt_utility_dt_instrumentation_dt_com_dh_ecim_dh_notification_dh_supervision_dh_handler_cl_type_eq_ComEcimNotificationInstrumentation_nm_totalBufferedNotifications{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "mspmPullFilesTransferTime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesTransferTime{site=\"$site\"}[$__rate_interval])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "mspmPullFilesStoredFS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jboss_dh_com_dt_ericsson_dt_oss_dt_mediation_dt_ftp_dt_instrumentation_dt_MultipleFileCollectionHandler_cl_type_eq_PmFileCollectionMetricInstrumentation_nm_mspmPullFilesStoredFS{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average neo4j_bolt_accumulated_processing_time_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(neo4j_bolt_accumulated_processing_time_total{site=\"$site\"}[$__rate_interval])) by (pod) / sum(rate(neo4j_bolt_messages_done_total{site=\"$site\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader - Average neo4j_bolt_accumulated_processing_time_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(neo4j_bolt_accumulated_processing_time_total{site=\"$site\"}[$__rate_interval]) * on (pod) group_left(pod) neo4j_dps_causal_clustering_core_is_leader{site=\"$site\"})  by (pod) / sum(rate(neo4j_bolt_messages_done_total{site=\"$site\"}[$__rate_interval]) * on (pod) group_left(pod) neo4j_dps_causal_clustering_core_is_leader{site=\"$site\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WriteTxCount / WriteTransactionClosingTime ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(jboss_dh_com_dt_ericsson_dt_oss_dt_itpf_dt_datalayer_dt_dps_dt_neo4j_dt_jca_dt_instrumentation_cl_type_eq_Neo4jTransaction_nm_WriteTxCount{site=\"$site\"}[$__rate_interval])\r\n/\r\nsum(jboss_dh_com_dt_ericsson_dt_oss_dt_itpf_dt_datalayer_dt_dps_dt_neo4j_dt_jca_dt_instrumentation_cl_type_eq_Neo4jTransaction_nm_WriteTransactionClosingTime{site=\"$site\"}[$__rate_interval])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}