{
 "title": "JBoss JVM",
 "tags": [
  "ENM",
  "PLATFORM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(jboss_dh_jvmgc_nm_young_dh_time, site)"
    }
   },
   {
    "name": "sg",
    "query": {
     "query": "label_values(jboss_dh_jvmgc_nm_young_dh_time{site=\"$site\"},sg)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(jboss_dh_os_nm_ProcessCpuTime{site=\"$site\",sg=~\"$sg\"}[$__rate_interval])",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jboss_dh_jvm_dh_memory_nm_HeapMemoryUsage_dh_used{site=\"$site\",sg=~\"$sg\"}",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jboss_dh_threads_nm_ThreadCount{site=\"$site\",sg=~\"$sg\"}",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jboss_dh_os_nm_OpenFileDescriptorCount{site=\"$site\",sg=~\"$sg\"}",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Young GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(jboss_dh_jvmgc_nm_young_dh_time{site=\"$site\",sg=~\"$sg\"}[$__rate_interval])",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Old GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(jboss_dh_jvmgc_nm_old_dh_time{site=\"$site\",sg=~\"$sg\"}[$__rate_interval])",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jboss_dh_lr_dh_jvm_dh_mem_dh_codecache_nm_Usage_dh_used{site=\"$site\",sg=~\"$sg\"}[$__rate_interval]",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Meta Data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jboss_dh_lr_dh_jvm_dh_mem_dh_meta_nm_Usage_dh_used{site=\"$site\",sg=~\"$sg\"}[$__rate_interval]",
     "legendFormat": "{{sg}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jboss_dh_lr_dh_jvm_dh_mem_dh_ccs_nm_Usage_dh_used{site=\"$site\",sg=~\"$sg\"}[$__rate_interval]",
     "legendFormat": "{{sg}}"
    }
   ]
  }
 ]
}