{
 "title": "Kubernetes cluster monitoring (via Prometheus) - By Site",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(cadvisor_version_info, site)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(cadvisor_version_info{site=\"$site\"}, node)"
    }
   },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=~\"^$Node$\", site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "0 - sum(rate(container_network_transmit_bytes_total{node=~\"^$Node$\", site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{id=\"/\", node=~\"^$Node$\", site=\"$site\"}) / sum(machine_memory_bytes{node=~\"^$Node$\", site=\"$site\"})) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{id=\"/\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) / sum(machine_cpu_cores{node=~\"^$Node$\", site=\"$site\"})) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\", id=\"/\", node=~\"^$Node$\", site=\"$site\"}) / sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\", id=\"/\", node=~\"^$Node$\", site=\"$site\"})) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\", node=~\"^$Node$\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{node=~\"^$Node$\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=~\"^$Node$\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\", id=\"/\", node=~\"^$Node$\", site=\"$site\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\", id=\"/\", node=~\"^$Node$\", site=\"$site\"})"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{systemd_service_name!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (container_name, pod)",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", name!~\"^k8s_.*\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{rkt_container_name!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id!=\"/\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", node=~\"^$Node$\", site=\"$site\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{systemd_service_name!=\"\", node=~\"^$Node$\", site=\"$site\"}) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"POD\", node=~\"^$Node$\", site=\"$site\"}) by (container_name, pod)",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", name!~\"^k8s_.*\", node=~\"^$Node$\", site=\"$site\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{rkt_container_name!=\"\", node=~\"^$Node$\", site=\"$site\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id!=\"/\", node=~\"^$Node$\", site=\"$site\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "0 - sum(rate(container_network_transmit_bytes_total{image!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (container_name, pod)",
       "legendFormat": "-> pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "0 - sum(rate(container_network_transmit_bytes_total{image!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (container_name, pod)",
       "legendFormat": "<- pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\", name!~\"^k8s_.*\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "0 - sum(rate(container_network_transmit_bytes_total{image!=\"\", name!~\"^k8s_.*\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{rkt_container_name!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "0 - sum(rate(container_network_transmit_bytes_total{rkt_container_name!=\"\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id!=\"/\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "0 - sum(rate(container_network_transmit_bytes_total{id!=\"/\", node=~\"^$Node$\", site=\"$site\"}[$__rate_interval])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}