{
 "title": "Neo4j",
 "description": "Neo4j cluster monitoring dashboard, with Prometheus data source.\nRead more at https://graphaware.com/neo4j/2019/06/11/monitoring-neo4j-prometheus.html",
 "tags": [
  "ENM",
  "PLATFORM"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(neo4j_dps_ids_in_use_relationship_type, site)"
    }
   },
   { "name": "job", "query": "neo4j" },
   {
    "name": "neo4j_pod",
    "label": "Neo4j instance",
    "query": {
     "query": "label_values(up{site=\"$site\",job=\"neo4j\"}, pod)"
    }
   },
   {
    "name": "leader",
    "query": {
     "query": "query_result(neo4j_dps_causal_clustering_core_is_leader {site=\"$site\"}== 1),"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "$neo4j_pod Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "repeat": "neo4j_pod",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$neo4j_pod Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$neo4j_pod Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Counters of Graph Items",
   "type": "graph",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dps_ids_in_use_(node|property|relationship)\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dps_ids_in_use_(.+)\")",
     "legendFormat": "{{label}} {{pod}}"
    },
    {
     "expr": "neo4j_dps_ids_in_use_relationship_type{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "relationship type {{pod}}"
    }
   ]
  },
  {
   "title": "Graph Items Creation Rate (ids)",
   "type": "graph",
   "description": "Per-second Average Rate of Increase of Data Counters",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_ids_in_use_node{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "Node rate {{pod}}"
    },
    {
     "expr": "rate(neo4j_dps_ids_in_use_relationship{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "Relationship rate {{pod}}"
    },
    {
     "expr": "rate(neo4j_dps_ids_in_use_property{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "Property rate {{pod}}"
    }
   ]
  },
  {
   "title": "Node creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_dps_ids_in_use_node{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])"
    }
   ]
  },
  {
   "title": "Relationship creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_dps_ids_in_use_relationship{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])"
    }
   ]
  },
  {
   "title": "Property creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_dps_ids_in_use_property{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last Closed Transaction ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "neo4j_dps_transaction_last_closed_tx_id_total{job=\"$job\", instance=~\"$leader\", site=\"$site\"}",
     "legendFormat": "Last Closed Write Transaction ID"
    }
   ]
  },
  {
   "title": "Committed Transaction Speed",
   "type": "singlestat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(neo4j_dps_transaction_committed_total{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])"
    }
   ]
  },
  {
   "title": "Rolled back Transaction Speed",
   "type": "singlestat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(neo4j_dps_transaction_rollbacks_total{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "All transaction metrics",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dps_transaction_(started|committed|rollbacks|terminated)_total\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dps_transaction_(.+)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Committed transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dps_transaction_committed_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "Total Committed Tr.s {{pod}}"
    },
    {
     "expr": "neo4j_dps_transaction_committed_read_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "Committed Read Tr.s {{pod}}"
    }
   ]
  },
  {
   "title": "Last Committed Write Transaction ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "neo4j_dps_transaction_last_committed_tx_id_total{job=\"$job\", instance=\"$leader\", site=\"$site\"}",
     "legendFormat": "Last Committed Transaction ID"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "graph",
   "description": "Active Transactions - Read and Write - \nand Peak concurrent",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dps_transaction_active_read{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "Active read {{pod}}"
    },
    {
     "expr": "neo4j_dps_transaction_active_write{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "Active write {{pod}}"
    },
    {
     "expr": "neo4j_dps_transaction_peak_concurrent_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "Peak concurrent {{pod}}"
    }
   ]
  },
  {
   "title": "Committed Read Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_transaction_committed_read_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Committed Write Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_transaction_committed_write_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "rate {{pod}}"
    }
   ]
  },
  {
   "title": "Committed Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_transaction_committed_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "rate {{pod}}"
    },
    {
     "expr": "irate(neo4j_dps_transaction_committed_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "iRate {{pod}}"
    }
   ]
  },
  { "title": "Bolt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Bolt Messages (done vs failed)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_messages_(done|failed)_total\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bolt Messages Queue",
   "type": "graph",
   "description": "Messages received - Messages started",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_bolt_messages_received_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"} - neo4j_bolt_messages_started_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "Bolt Msg Queue Length {{pod}}"
    },
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_messages_(received|started)_total\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bolt Rate of message queue time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_queue_time_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bolt Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_connections_.+\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_connections_(.+)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bolt Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_sessions.+\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_sessions_(.+)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bolt rate of message processing time",
   "type": "graph",
   "description": "Processing and Queuing time per bolt message",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_processing_time_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Page Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Page cache faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_page_faults_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page cache faults/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_page_faults_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page cache Pins and Unpins rate (pins/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_pins_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "pins {{pod}}"
    },
    {
     "expr": "rate(neo4j_page_cache_unpins_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "unpins {{pod}}"
    }
   ]
  },
  {
   "title": "Page cache evictions rate (evictions/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_evictions_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "evictions{{pod}}"
    },
    {
     "expr": "rate(neo4j_page_cache_eviction_exceptions_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "eviction exceptions {{pod}}"
    }
   ]
  },
  {
   "title": "Page cache evictions",
   "type": "graph",
   "description": "Eviction process in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_evictions_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page cache flushes",
   "type": "graph",
   "description": "The total number of flushes executed by the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_flushes_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits",
   "type": "graph",
   "description": "The total number of page hits happened in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_hits_total{job=\"$job\", site=\"$site\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits Rate (hits/sec)",
   "type": "graph",
   "description": "Per-second Neo4j Page Cache Hits",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_hits_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page cache flushes rate (flushes/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_flushes_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page Cache Hit Ratio",
   "type": "graph",
   "description": "The ratio of hits to the total number of lookups in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_hit_ratio{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Neo4j Log Rotation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dps_log_.+\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "graph",
   "description": "Neo4j Checkpoints. \nCheckpointing is the process of flushing all pending page updates from the page cache to the store files",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dps_check_point_(events|total_time)_total\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{pod}}"
    }
   ]
  },
  {
   "title": "Checkpoint event duration sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "neo4j_dps_check_point_check_point_duration{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "VM Garbage Collector",
   "type": "graph",
   "description": "Time and counters",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"neo4j_vm_gc_time_g1_.+_generation_total\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[1m])",
     "legendFormat": "{{__name__}} {{pod}}"
    },
    {
     "expr": "delta(neo4j_vm_gc_time_g1_old_generation_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "delta g1 old g total {{pod}}"
    },
    {
     "expr": "delta(neo4j_vm_gc_time_g1_young_generation_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}[$interval])",
     "legendFormat": "delta g1 young g total {{pod}}"
    }
   ]
  },
  {
   "title": "VM Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_vm_thread_count{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "vm live threads {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap Size",
   "type": "graph",
   "description": "Heap memory (eden space, old generation, survivor space)\nNon-heap memory (metaspace, compressed class space, code cache)",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"neo4j_vm_memory_pool_g1_(eden|old|survivor).*\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}) by (instance)",
     "legendFormat": "{{pod}} heap"
    },
    {
     "expr": "sum({__name__=~\"neo4j_vm_memory_pool_(code|compressed|metaspace).*\", job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}) by (instance)",
     "legendFormat": "{{pod}} non-heap"
    }
   ]
  },
  {
   "title": "JVM Used Buffer rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 109 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "neo4j_vm_memory_buffer_direct_used{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "memory buffer direct used {{pod}}"
    },
    {
     "expr": "neo4j_vm_memory_buffer_mapped_used{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "memory buffer mapped used{{pod}}"
    }
   ]
  },
  { "title": "Causal Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Committed read transaction rate - Leader Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_transaction_committed_read_total{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])",
     "legendFormat": "Leader {{pod}}"
    },
    {
     "expr": "sum(rate(neo4j_dps_transaction_committed_read_total{job=\"$job\", instance!=\"$leader\", site=\"$site\"}[$interval]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Committed write transaction rate - Leader Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_transaction_committed_write_total{job=\"$job\", instance=\"$leader\", site=\"$site\"}[$interval])",
     "legendFormat": "Leader {{pod}}"
    },
    {
     "expr": "sum(rate(neo4j_dps_transaction_committed_write_total{job=\"$job\", instance!=\"$leader\", site=\"$site\"}[$interval]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Replicate pulls rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dps_causal_clustering_read_replica_pull_updates_total{site=\"$site\"}[$interval])"
    }
   ]
  },
  {
   "title": "Core message processing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "neo4j_dps_causal_clustering_core_message_processing_timer{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"} * 10000",
     "legendFormat": "{{quantile}} {{pod}}"
    }
   ]
  },
  {
   "title": "Core election timeout ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dps_causal_clustering_core_message_processing_timer_election_timeout{job=\"$job\", pod=~\"$neo4j_pod\", quantile=\"0.5\", site=\"$site\"} * 10000",
     "legendFormat": "median {{pod}}"
    },
    {
     "expr": "neo4j_dps_causal_clustering_core_message_processing_timer_election_timeout_count{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "count {{pod}}"
    }
   ]
  },
  { "title": "Cypher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Cyper replan events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_cypher_replan_events_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{__name__}} {{pod}}"
    }
   ]
  },
  {
   "title": "Cyper wait time",
   "type": "graph",
   "description": "The total number of seconds waited between query replans",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "neo4j_cypher_replan_wait_time_total{job=\"$job\", pod=~\"$neo4j_pod\", site=\"$site\"}",
     "legendFormat": "{{__name__}} {{pod}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } }
 ]
}