{
 "title": "SSO AM",
 "tags": [
  "ENM_APP",
  "The16th"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(ds_current_connections,site)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CTS CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Seconds",
     "type": "timeseries",
     "description": "This graph represents the number of seconds of CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "increase(container_cpu_usage_seconds_total{container=\"cts\",cpu=\"total\",endpoint=\"https-metrics\",job=\"kubelet-cadvisor\",metrics_path=\"/metrics/cadvisor\",service=\"eric-enm-kubelet\",site=\"$site\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU seconds throttled",
     "type": "timeseries",
     "description": "This graph represents the number of seconds of CPU throttling.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_seconds_total{container=\"cts\",endpoint=\"https-metrics\",job=\"kubelet-cadvisor\",metrics_path=\"/metrics/cadvisor\",service=\"eric-enm-kubelet\",site=\"$site\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CTS metric (DS side)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Degraded Index",
     "type": "timeseries",
     "description": "The number of degraded indexes across all DS backends",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(ds_backend_degraded_index_count{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Persistent-Searches",
     "type": "timeseries",
     "description": "Total number of active LDAP persistent searches.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(ds_connection_handlers_ldap_active_persistent_searches{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}) by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "description": "Total number of active LDAP & HTTP connections",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(ds_current_connections{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests Waiting in Queue",
     "type": "timeseries",
     "description": "Total number of work requests currently queued waiting to be processed per DS instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(ds_work_queue_requests_in_queue{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average LDAP success request Service Time",
     "type": "timeseries",
     "description": "The average time taken to process a request over the displayed time range. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (pod) (irate(ds_connection_handlers_ldap_requests_seconds_total{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}[$__rate_interval]))) / (sum by (pod) (irate(ds_connection_handlers_ldap_requests_count{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average LDAP failure Request Service Time",
     "type": "timeseries",
     "description": "The average time taken to process a request over the displayed time range",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (pod) (irate(ds_connection_handlers_ldap_requests_failure_seconds_total{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}[$__rate_interval]))) / (sum by (pod) (irate(ds_connection_handlers_ldap_requests_failure_count{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LDAP Request Throughput",
     "type": "timeseries",
     "description": "Number of LDAP requests processed over the displayed time range",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (pod) (irate(ds_connection_handlers_ldap_requests_count{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}[$__rate_interval])) or sum by (pod) (irate(ds_connection_handlers_ldap_requests_failure_count{app=\"cts\",endpoint=\"metrics\",job=\"cts\",service=\"cts\",site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy / Authorization metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allowed Authorization request (ENMPolicies Set)",
     "type": "timeseries",
     "description": "The sum of the values of allowed actions being returned under a given policy set (ENMPolicies).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum(increase(am_authorization_policy_set_evaluate_action_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",outcome=\"allow\",policy_set=\"ENMPolicies\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Denied Authorization request (ENMPolicies Set)",
     "type": "timeseries",
     "description": "The sum of the values of denied actions being returned under a given policy set (ENMPolicies).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "sum(increase(am_authorization_policy_set_evaluate_action_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",outcome=\"deny\",policy_set=\"ENMPolicies\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Evaluation Throughput (ENMPolicies Set)",
     "type": "timeseries",
     "description": "The number of success actions being returned under a given policy set (ENMPolicies).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum(increase(am_authorization_policy_set_evaluate_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",outcome=\"success\",policy_set=\"ENMPolicies\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Evaluation Service Time (ENMPolicies Set)",
     "type": "timeseries",
     "description": "Time taken to perform policy evaluation calls under a given policy set (ENMPolicies Set).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum(rate(am_authorization_policy_set_evaluate_seconds_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",outcome=\"success\",policy_set=\"ENMPolicies\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval]) / rate(am_authorization_policy_set_evaluate_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",outcome=\"success\",policy_set=\"ENMPolicies\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Session metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Session Creation Throughput",
     "type": "timeseries",
     "description": "Total number of successfully created sessions.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum(increase(am_session_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",operation=~\"create\",outcome=\"success\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "SessionCreationThroughput"
      }
     ]
    },
    {
     "title": "Total Session Termination Throughput",
     "type": "timeseries",
     "description": "Total number of successfully terminated sessions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum(increase(am_session_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",operation=~\"logout|destroy|idle-timeout|max-timeout\",outcome=\"success\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval]))",
       "legendFormat": "TotalSessionTerminationThroughput"
      }
     ]
    },
    {
     "title": "Overall Average Session Lifetime",
     "type": "timeseries",
     "description": "Total session lifetime in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "avg(rate(am_session_lifetime_seconds_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"})[$__rate_interval])",
       "legendFormat": "OverallAverageSessionLifetime"
      }
     ]
    }
   ]
  },
  {
   "title": "Authentication metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP Module success auth requests",
     "type": "timeseries",
     "description": "Number of successful authentication requests for LDAP auth module.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "increase(sum(am_authentication_module_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",module=\"LDAP\",outcome=\"success\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval]) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LDAP module failed auth requests",
     "type": "timeseries",
     "description": "Number of failed authentication requests for LDAP auth module.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "increase(sum(am_authentication_module_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",module=\"LDAP\",outcome=\"failure\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval]) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CustomLDAP module success auth requests",
     "type": "timeseries",
     "description": "Number of successful authentication requests for CustomLDAP auth module.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "increase(sum(am_authentication_module_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",module=\"CustomLDAP\",outcome=\"success\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval]) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CustomLDAP module failed auth requests",
     "type": "timeseries",
     "description": "Number of failed authentication requests for CustomLDAP auth module.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "increase(sum(am_authentication_module_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",module=\"CustomLDAP\",outcome=\"failure\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval]) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Web Agent success auth requests",
     "type": "timeseries",
     "description": "Number of successful authentication requests for Application module.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "increase(sum(am_authentication_module_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",module=\"Application\",outcome=\"success\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval]) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Web Agent failed auth requests",
     "type": "timeseries",
     "description": "Number of failed authentication requests for Application module.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "increase(sum(am_authentication_module_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",module=\"Application\",outcome=\"failure\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval]) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CTS metrics (AM side)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CTS Overall Average Task Queueing Time",
     "type": "timeseries",
     "description": "Average queueing times for CTS operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(am_cts_task_queue_seconds_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval]) / rate(am_cts_task_queue_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS Total Tasks Waiting in Queue",
     "type": "timeseries",
     "description": "Number of operations waiting in a CTS queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(am_cts_task_queue_size{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS Total Tasks Throughput",
     "type": "timeseries",
     "description": "CTS Total Tasks Throughput",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(increase(am_cts_task_queue_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS reaper cache size",
     "type": "timeseries",
     "description": "CTS reaper cache size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(am_cts_reaper_cache_size{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS Overall Average Task Service Time",
     "type": "timeseries",
     "description": "CTS Overall Average Task Service Time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(am_cts_task_seconds_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\",token_type=\"session\"}[$__rate_interval])/ rate(am_cts_task_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\",token_type=\"session\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CTS Overall Average Connections Service Time",
     "type": "timeseries",
     "description": "CTS Overall Average Connections Service Time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(am_cts_connection_seconds_total{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval]) / rate(am_cts_connection_count{app=\"sso\",endpoint=\"metrics\",job=\"sso-am-prometheus\",service=\"sso-am-prometheus\",sgname=\"sso\",site=\"$site\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}